export const shapesTemplates = {
  'shapes.identify.visual-to-text': {
    id: 'shapes.identify.visual-to-text',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'visual_to_text', difficulty: 'easy' },
  },
  'shapes.identify.text-to-visual': {
    id: 'shapes.identify.text-to-visual',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'text_to_visual', difficulty: 'easy' },
  },
  'shapes.remedial.match': {
    id: 'shapes.remedial.match',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'remedial_match_basic' },
  },
  'shapes.remedial.sides': {
    id: 'shapes.remedial.sides',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'remedial_count_sides' },
  },
  'shapes.3d.identify': {
    id: 'shapes.3d.identify',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'shapes-g2-2d-vs-3d' },
  },
  'shapes.3d.properties': {
    id: 'shapes.3d.properties',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'shapes-g2-vertices-edges-faces' },
  },
  'shapes.quadrilaterals': {
    id: 'shapes.quadrilaterals',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'shapes-g3-quadrilaterals' },
  },
  'shapes.symmetry.lines': {
    id: 'shapes.symmetry.lines',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'shapes-g3-symmetry-lines' },
  },
  'shapes.symmetry.check': {
    id: 'shapes.symmetry.check',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'shapes-g3-symmetry-check' },
  },
  'shapes.ukg.name': {
    id: 'shapes.ukg.name',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_shapes_name' },
  },
  'shapes.ukg.circles': {
    id: 'shapes.ukg.circles',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_circles' },
  },
  'shapes.ukg.triangles': {
    id: 'shapes.ukg.triangles',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_triangles' },
  },
  'shapes.ukg.squares_rectangles': {
    id: 'shapes.ukg.squares_rectangles',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_squares_rectangles' },
  },
  'shapes.ukg.hexagons': {
    id: 'shapes.ukg.hexagons',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_hexagons' },
  },
  'shapes.ukg.select_2d': {
    id: 'shapes.ukg.select_2d',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_select_2d' },
  },
  'shapes.ukg.count_sides_corners': {
    id: 'shapes.ukg.count_sides_corners',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_count_sides_corners' },
  },
  'shapes.ukg.compare_sides_corners': {
    id: 'shapes.ukg.compare_sides_corners',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_compare_sides_corners' },
  },
  'shapes.ukg.intro_symmetry': {
    id: 'shapes.ukg.intro_symmetry',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_intro_symmetry' },
  },
  'shapes.ukg.pictures_symmetry': {
    id: 'shapes.ukg.pictures_symmetry',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_pictures_symmetry' },
  },
  'shapes.ukg.two_three_3d': {
    id: 'shapes.ukg.two_three_3d',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_two_three_3d' },
  },
  'shapes.ukg.name_3d': {
    id: 'shapes.ukg.name_3d',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_name_3d' },
  },
  'shapes.ukg.spheres': {
    id: 'shapes.ukg.spheres',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_spheres' },
  },
  'shapes.ukg.cubes': {
    id: 'shapes.ukg.cubes',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_cubes' },
  },
  'shapes.ukg.cones': {
    id: 'shapes.ukg.cones',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_cones' },
  },
  'shapes.ukg.cylinders': {
    id: 'shapes.ukg.cylinders',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_cylinders' },
  },
  'shapes.ukg.select_3d': {
    id: 'shapes.ukg.select_3d',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_select_3d' },
  },
  'shapes.ukg.traced_solids': {
    id: 'shapes.ukg.traced_solids',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_traced_solids' },
  },
  'shapes.ukg.everyday_objects_1': {
    id: 'shapes.ukg.everyday_objects_1',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_everyday_objects_1' },
  },
  'shapes.ukg.everyday_objects_2': {
    id: 'shapes.ukg.everyday_objects_2',
    family: 'shapes',
    engine: 'shapes',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'ukg_everyday_objects_2' },
  }
};

export function getShapesTemplate(templateId) {
  return shapesTemplates[templateId] || null;
}
