import { NextResponse } from 'next/server';
import { getMongoDb } from '@/lib/db/mongo';

/**
 * POST /api/admin/templates/clear-cache
 * Deletes cached questions from the `questions` collection
 * that were generated from a specific template (or all templates).
 *
 * Body:
 *   { templateId: "template-xyz" }         → clear one template
 *   { templateId: "all" }                  → clear ALL template-generated questions
 *   { templateIds: ["id-1", "id-2"] }      → clear multiple templates
 */
export async function POST(req) {
  try {
    const body = await req.json();
    const { templateId, templateIds } = body;

    if (!templateId && !templateIds) {
      return NextResponse.json(
        { success: false, error: 'Provide templateId (string or "all") or templateIds (array).' },
        { status: 400 }
      );
    }

    const db = await getMongoDb();
    if (!db) {
      return NextResponse.json({ success: false, error: 'Database not available.' }, { status: 503 });
    }

    let filter = {};

    if (templateId === 'all') {
      // Delete all questions that have a templateId set (i.e. were generated by a template)
      filter = { templateId: { $exists: true, $ne: null, $ne: '' } };
    } else if (Array.isArray(templateIds) && templateIds.length > 0) {
      filter = { templateId: { $in: templateIds } };
    } else if (typeof templateId === 'string' && templateId) {
      filter = { templateId };
    } else {
      return NextResponse.json(
        { success: false, error: 'Invalid templateId value.' },
        { status: 400 }
      );
    }

    // Count before deleting
    const countBefore = await db.collection('questions').countDocuments(filter);

    if (countBefore === 0) {
      return NextResponse.json({
        success: true,
        deleted: 0,
        message: 'No cached questions found for this template.',
      });
    }

    const result = await db.collection('questions').deleteMany(filter);

    return NextResponse.json({
      success: true,
      deleted: result.deletedCount,
      message: `Cleared ${result.deletedCount} cached question(s). Fresh questions will be generated on next practice session.`,
    });
  } catch (err) {
    console.error('[clear-cache] Error:', err);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}

/**
 * GET /api/admin/templates/clear-cache?templateId=xxx
 * Returns the count of cached questions for a template (preview before deleting).
 */
export async function GET(req) {
  try {
    const { searchParams } = new URL(req.url);
    const templateId = searchParams.get('templateId');

    const db = await getMongoDb();
    if (!db) {
      return NextResponse.json({ success: false, error: 'Database not available.' }, { status: 503 });
    }

    if (templateId === 'all' || !templateId) {
      // Count total cached template-generated questions
      const total = await db.collection('questions').countDocuments({
        templateId: { $exists: true, $ne: null, $ne: '' }
      });

      // Group by templateId
      const breakdown = await db.collection('questions').aggregate([
        { $match: { templateId: { $exists: true, $ne: null, $ne: '' } } },
        { $group: { _id: '$templateId', count: { $sum: 1 } } },
        { $sort: { count: -1 } }
      ]).toArray();

      return NextResponse.json({ success: true, total, breakdown });
    }

    const count = await db.collection('questions').countDocuments({ templateId });
    return NextResponse.json({ success: true, templateId, count });
  } catch (err) {
    console.error('[clear-cache] GET Error:', err);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
