export const placeValueTemplates = {
  'place-values.blocks.units': {
    id: 'place-values.blocks.units',
    family: 'blocks',
    engine: 'blocks',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'identify_from_blocks', difficulty: 'easy' },
  },
  'place-values.blocks.match-number': {
    id: 'place-values.blocks.match-number',
    family: 'blocks',
    engine: 'blocks',
    questionType: 'mcq',
    defaultConfig: {
      forcedTask: 'match_blocks_to_number',
      difficulty: 'adaptive',
      optionCount: 4,
    },
  },
  'place-values.blocks.hundreds': {
    id: 'place-values.blocks.hundreds',
    family: 'blocks',
    engine: 'blocks',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'identify_from_blocks_3d', difficulty: 'medium' },
  },
  'place-values.blocks.thousands': {
    id: 'place-values.blocks.thousands',
    family: 'blocks',
    engine: 'blocks',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'thousands_blocks', difficulty: 'hard' },
  },
  'place-values.place-name': {
    id: 'place-values.place-name',
    family: 'placeName',
    engine: 'placeName',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'place_name', difficulty: 'easy' },
  },
  'place-values.expanded-form': {
    id: 'place-values.expanded-form',
    family: 'expandedForm',
    engine: 'expandedForm',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'expanded_form', difficulty: 'medium' },
  },
  'place-values.word-to-number': {
    id: 'place-values.word-to-number',
    family: 'wordToNumber',
    engine: 'wordToNumber',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'word_to_number', difficulty: 'hard' },
  },
  'place-values.breakdown-table': {
    id: 'place-values.breakdown-table',
    family: 'expandedForm',
    engine: 'expandedForm',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'breakdown_table', difficulty: 'medium' },
  },
  'place-values.comma.indian': {
    id: 'place-values.comma.indian',
    family: 'indianSystem',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'indian_comma_grouping', difficulty: 'medium' },
  },
  'place-values.comma.international': {
    id: 'place-values.comma.international',
    family: 'internationalSystem',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'international_comma_grouping', difficulty: 'medium' },
  },
  'place-values.chart.large': {
    id: 'place-values.chart.large',
    family: 'indianSystem',
    engine: 'system',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'indian_place_chart', difficulty: 'medium' },
  },
  'place-values.expanded-form.large': {
    id: 'place-values.expanded-form.large',
    family: 'expandedForm',
    engine: 'system',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'expanded_form_large', difficulty: 'medium' },
  },
  'place-values.compare.large': {
    id: 'place-values.compare.large',
    family: 'compareNumbers',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'compare_large_numbers', difficulty: 'medium' },
  },
  'place-values.order.large': {
    id: 'place-values.order.large',
    family: 'orderNumbers',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'order_large_numbers', difficulty: 'medium' },
  },
  'place-values.rounding.nearest-thousand': {
    id: 'place-values.rounding.nearest-thousand',
    family: 'rounding',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'rounding_number_line', difficulty: 'medium' },
  },
  'place-values.rounding.nearest-lakh': {
    id: 'place-values.rounding.nearest-lakh',
    family: 'rounding',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'rounding_nearest_lakh', difficulty: 'hard' },
  },
  'place-values.decomposition.button-machine': {
    id: 'place-values.decomposition.button-machine',
    family: 'buttonMachine',
    engine: 'system',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'button_machine_decomposition', difficulty: 'medium' },
  },
  'place-values.magnitude.benchmark': {
    id: 'place-values.magnitude.benchmark',
    family: 'numberMagnitude',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'magnitude_benchmark', difficulty: 'medium' },
  },
  'place-values.shortcut-multiplication': {
    id: 'place-values.shortcut-multiplication',
    family: 'shortcutMultiplication',
    engine: 'system',
    questionType: 'fillInTheBlank',
    defaultConfig: { forcedTask: 'shortcut_multiplication', difficulty: 'medium' },
  },
  'place-values.system.conversion': {
    id: 'place-values.system.conversion',
    family: 'systemConversion',
    engine: 'system',
    questionType: 'mcq',
    defaultConfig: { forcedTask: 'system_conversion', difficulty: 'hard' },
  },
};

export function getPlaceValueTemplate(templateId) {
  return placeValueTemplates[templateId] || null;
}
