/**
 * Skills definition – Chemical Reactions & Equations (Grade 10 Science)
 *
 * Granular IXL-style micro-skill tree covering the entire chapter in details.
 */

export const grade10ChemReactionSkills = [
  {
    id: 'cr-g10-identify-reaction-easy',
    code: 'CR.1.R',
    title: 'Identify physical vs chemical changes (Remediation)',
    templateId: 'science-chemical-reactions-cr1-easy',
    competencyId: 'cr_identify_remediation',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'easy',
    engine: 'universal-template',
    prereqs: [],
    unlocks: ['cr-g10-identify-reaction'],
  },
  {
    id: 'cr-g10-identify-reaction',
    code: 'CR.1',
    title: 'Identify chemical reaction indicators and signs',
    templateId: 'science-chemical-reactions-cr1',
    competencyId: 'cr_identify',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'easy',
    engine: 'universal-template',
    prereqs: [],
    unlocks: ['cr-g10-observe-experiments'],
  },
  {
    id: 'cr-g10-observe-experiments',
    code: 'CR.2',
    title: 'Observe and analyze chemical experiments (Activities 1.1 - 1.3)',
    templateId: 'science-chemical-reactions-cr2',
    competencyId: 'cr_experiments',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'easy',
    engine: 'universal-template',
    prereqs: ['cr-g10-identify-reaction'],
    unlocks: ['cr-g10-write-equations'],
  },
  {
    id: 'cr-g10-write-equations',
    code: 'CR.3',
    title: 'Represent chemical reactions (Word & Skeletal Equations)',
    templateId: 'science-chemical-reactions-cr3',
    competencyId: 'cr_write_eq',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'easy',
    engine: 'universal-template',
    prereqs: ['cr-g10-observe-experiments'],
    unlocks: ['cr-g10-balance-equations'],
  },
  {
    id: 'cr-g10-balance-equation',
    code: 'CR.4',
    title: 'Balance chemical equations (Coefficients & Law of Conservation)',
    templateId: 'science-chemical-reactions-cr4',
    competencyId: 'cr_balance_eq',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'medium',
    engine: 'universal-template',
    prereqs: ['cr-g10-write-equations'],
    unlocks: ['cr-g10-combination-reactions'],
  },
  {
    id: 'cr-g10-combination-reactions',
    code: 'CR.5',
    title: 'Classify combination reactions and exothermic processes',
    templateId: 'science-chemical-reactions-cr5',
    competencyId: 'cr_combination',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'medium',
    engine: 'universal-template',
    prereqs: ['cr-g10-balance-equation'],
    unlocks: ['cr-g10-decomposition-reactions'],
  },

  {
    id: 'cr-g10-decomposition-reactions',
    code: 'CR.6',
    title: 'Classify decomposition reactions and endothermic processes',
    templateId: 'science-chemical-reactions-cr6',
    competencyId: 'cr_decomposition',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'medium',
    engine: 'universal-template',
    prereqs: ['cr-g10-combination-reactions'],
    unlocks: ['cr-g10-displacement-reactions'],
  },
  {
    id: 'cr-g10-displacement-reactions',
    code: 'CR.7',
    title: 'Classify single displacement reactions & reactivity series',
    templateId: 'science-chemical-reactions-cr7',
    competencyId: 'cr_displacement',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'medium',
    engine: 'universal-template',
    prereqs: ['cr-g10-decomposition-reactions'],
    unlocks: ['cr-g10-double-displacement'],
  },
  {
    id: 'cr-g10-double-displacement',
    code: 'CR.8',
    title: 'Classify double displacement & precipitation reactions',
    templateId: 'science-chemical-reactions-cr8',
    competencyId: 'cr_double_displacement',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'medium',
    engine: 'universal-template',
    prereqs: ['cr-g10-displacement-reactions'],
    unlocks: ['cr-g10-redox-reactions'],
  },
  {
    id: 'cr-g10-redox-reactions',
    code: 'CR.9',
    title: 'Identify oxidation and reduction in redox reactions',
    templateId: 'science-chemical-reactions-cr9',
    competencyId: 'cr_redox',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'hard',
    engine: 'universal-template',
    prereqs: ['cr-g10-double-displacement'],
    unlocks: ['cr-g10-oxidation-everyday'],
  },
  {
    id: 'cr-g10-oxidation-everyday',
    code: 'CR.10',
    title: 'Analyze oxidation in everyday life (Corrosion & Rancidity)',

    templateId: 'science-chemical-reactions-cr10',
    competencyId: 'cr_everyday_oxidation',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'hard',
    engine: 'universal-template',
    prereqs: ['cr-g10-redox-reactions'],
    unlocks: ['cr-g10-passage-analysis'],
  },
  {
    id: 'cr-g10-passage-analysis',
    code: 'CR.11',
    title: 'Identify reaction types in experimental passages (Sentence Select)',
    templateId: 'science-chemical-reactions-cr11',
    competencyId: 'cr_passage_analysis',
    grade: 10,
    subject: 'science',
    topic: 'chemical-reactions',
    difficulty: 'hard',
    engine: 'universal-template',
    prereqs: ['cr-g10-oxidation-everyday'],
    unlocks: [],
  },
];

