const chapter = (title, entries) => entries.map(([code, skillId, skillTitle, mode, limit, extraParams = {}]) => ({
  code,
  skillId,
  title: skillTitle,
  grade: 'UKG',
  chapter: title,
  templateId: `ukg.numbers.${mode}`,
  params: { mode, limit, ...extraParams }
}));

export const ukgNumbersCountingSkills = [
  ...chapter('Numbers and counting up to 3', [
    ['A.1', 'ukg-count3-learn', 'Learn to count to 3', 'learn', 3],
    ['A.2', 'ukg-count3-count', 'Count to 3', 'count', 3],
    ['A.3', 'ukg-count3-stickers', 'Count using stickers - up to 3', 'stickers', 3],
    ['A.4', 'ukg-count3-ten-frame-count', 'Count on ten frames - up to 3', 'ten_frame_count', 3],
    ['A.5', 'ukg-count3-ten-frame-show', 'Show numbers on ten frames - up to 3', 'ten_frame_show', 3],
    ['A.6', 'ukg-count3-represent', 'Represent numbers - up to 3', 'represent', 3],
  ]),
  ...chapter('Numbers and counting up to 5', [
    ['B.1', 'ukg-count5-learn', 'Learn to count to 5', 'learn', 5],
    ['B.2', 'ukg-count5-count', 'Count to 5', 'count', 5],
    ['B.3', 'ukg-count5-stickers', 'Count using stickers - up to 5', 'stickers', 5],
    ['B.4', 'ukg-count5-ten-frame-count', 'Count on ten frames - up to 5', 'ten_frame_count', 5],
    ['B.5', 'ukg-count5-ten-frame-show', 'Show numbers on ten frames - up to 5', 'ten_frame_show', 5],
    ['B.6', 'ukg-count5-represent', 'Represent numbers - up to 5', 'represent', 5],
    ['B.7', 'ukg-count5-one-more', 'One more - up to 5', 'one_more', 5],
    ['B.8', 'ukg-count5-count-one-more', 'Count one more - up to 5', 'count_one_more', 5],
    ['B.9', 'ukg-count5-one-less', 'One less - up to 5', 'one_less', 5],
    ['B.10', 'ukg-count5-count-one-less', 'Count one less - up to 5', 'count_one_less', 5],
  ]),
  ...chapter('Numbers and counting up to 10', [
    ['C.1', 'ukg-count10-learn', 'Learn to count to 10', 'learn', 10],
    ['C.2', 'ukg-count10-count', 'Count to 10', 'count', 10],
    ['C.3', 'ukg-count10-stickers', 'Count using stickers - up to 10', 'stickers', 10],
    ['C.4', 'ukg-count10-ten-frame-count', 'Count on ten frames - up to 10', 'ten_frame_count', 10],
    ['C.5', 'ukg-count10-ten-frame-show', 'Show numbers on ten frames - up to 10', 'ten_frame_show', 10],
    ['C.6', 'ukg-count10-represent', 'Represent numbers - up to 10', 'represent', 10],
    ['C.7', 'ukg-count10-one-more', 'One more - up to 10', 'one_more', 10],
    ['C.8', 'ukg-count10-count-one-more', 'Count one more - up to 10', 'count_one_more', 10],
    ['C.9', 'ukg-count10-one-less', 'One less - up to 10', 'one_less', 10],
    ['C.10', 'ukg-count10-count-one-less', 'Count one less - up to 10', 'count_one_less', 10],
    ['C.11', 'ukg-count10-one-more-less', 'One more and one less - up to 10', 'one_more_less', 10],
    ['C.12', 'ukg-count10-count-one-more-less', 'Count one more and one less - up to 10', 'count_one_more_less', 10],
    ['C.13', 'ukg-count10-next-number', 'Count up and down to find the next number - up to 10', 'next_number', 10],
    ['C.14', 'ukg-count10-fill-ten-frame', 'Count to fill a ten frame', 'fill_ten_frame', 10],
    ['C.15', 'ukg-count10-tally-marks', 'Tally marks - up to 10', 'tally_marks', 10],
    ['C.16', 'ukg-count10-number-line', 'Number lines - up to 10', 'number_line', 10],
    ['C.17', 'ukg-count10-before-after-between', 'Before, after and between - up to 10', 'before_after_between', 10],
    ['C.18', 'ukg-count10-forward-backward', 'Count forward and backward - up to 10', 'forward_backward', 10],
    ['C.19', 'ukg-count10-number-names', 'Names of numbers - up to 10', 'number_names', 10],
    ['C.20', 'ukg-count10-complete-sequence', 'Complete a sequence - up to 10', 'complete_sequence', 10],
  ]),
  ...chapter('Numbers and counting up to 20', [
    ['D.1', 'ukg-count20-count', 'Count to 20', 'count', 20],
    ['D.2', 'ukg-count20-ten-frame-count', 'Count on ten frames - up to 20', 'ten_frame_count', 20],
    ['D.3', 'ukg-count20-ten-frame-show', 'Show numbers on ten frames - up to 20', 'ten_frame_show', 20],
    ['D.4', 'ukg-count20-represent', 'Represent numbers - up to 20', 'represent', 20],
    ['D.5', 'ukg-count20-next-number', 'Count up and down to find the next number - up to 20', 'next_number', 20],
    ['D.6', 'ukg-count20-tally-marks', 'Tally marks - up to 20', 'tally_marks', 20],
    ['D.7', 'ukg-count20-number-line', 'Number lines - up to 20', 'number_line', 20],
    ['D.8', 'ukg-count20-before-after-between', 'Before, after and between - up to 20', 'before_after_between', 20],
    ['D.9', 'ukg-count20-forward-backward', 'Count forward and backward - up to 20', 'forward_backward', 20],
    ['D.10', 'ukg-count20-number-names', 'Names of numbers - up to 20', 'number_names', 20],
    ['D.11', 'ukg-count20-complete-sequence', 'Complete a sequence - up to 20', 'complete_sequence', 20],
    ['D.12', 'ukg-count20-tens-ones', 'Count tens and ones - up to 20', 'tens_ones', 20],
    ['D.13', 'ukg-count20-learn-skip-twos', 'Learn to skip-count by twos', 'learn_skip_twos', 20, { step: 2 }],
    ['D.14', 'ukg-count20-skip-twos', 'Skip-count by twos', 'skip_twos', 20, { step: 2 }],
    ['D.15', 'ukg-count20-skip-twos-ten-frames', 'Skip-count by twos on ten frames', 'skip_twos_ten_frames', 20, { step: 2 }],
  ]),
  ...chapter('Comparing', [
    ['E.1', 'ukg-comparing-enough', 'Are there enough?', 'compare_enough', 10],
    ['E.2', 'ukg-comparing-matching', 'Fewer and more - compare by matching', 'compare_matching', 10],
    ['E.3', 'ukg-comparing-counting', 'Fewer and more - compare by counting', 'compare_counting', 10],
    ['E.4', 'ukg-comparing-mixed-group', 'Fewer and more - compare in a mixed group', 'compare_mixed', 10],
    ['E.5', 'ukg-comparing-fewer-more-same', 'Fewer, more and same', 'compare_fewer_more_same', 10],
    ['E.6', 'ukg-comparing-two-numbers', 'Compare two numbers - up to 10', 'compare_two_numbers', 10],
    ['E.7', 'ukg-comparing-three-numbers', 'Compare three numbers - up to 10', 'compare_three_numbers', 10],
  ]),
  ...chapter('Patterns', [
    ['F.1', 'ukg-patterns-colour', 'Colour patterns', 'pattern_colour', 10],
    ['F.2', 'ukg-patterns-size', 'Size patterns', 'pattern_size', 10],
    ['F.3', 'ukg-patterns-shape', 'Shape patterns', 'pattern_shape', 10],
    ['F.4', 'ukg-patterns-next-shape', 'Find the next shape in a pattern', 'pattern_next_shape', 10],
    ['F.5', 'ukg-patterns-complete', 'Complete a pattern', 'pattern_complete', 10],
    ['F.6', 'ukg-patterns-growing', 'Growing patterns', 'pattern_growing', 10],
    ['F.7', 'ukg-patterns-growing-next-shape', 'Find the next shape in a growing pattern', 'pattern_growing_next_shape', 10],
    ['F.8', 'ukg-patterns-growing-next-row', 'Find the next row in a growing pattern', 'pattern_growing_next_row', 10],
  ]),
  ...chapter('Positions', [
    ['G.1', 'ukg-positions-inside-outside', 'Inside and outside', 'position_inside_outside', 10],
    ['G.2', 'ukg-positions-above-below', 'Above and below', 'position_above_below', 10],
    ['G.3', 'ukg-positions-above-below-solid-figures', 'Above and below - find solid figures', 'position_above_below_solid_figures', 10],
    ['G.4', 'ukg-positions-beside-next-to', 'Beside and next to', 'position_beside_next_to', 10],
    ['G.5', 'ukg-positions-beside-next-to-solid-figures', 'Beside and next to - find solid figures', 'position_beside_next_to_solid_figures', 10],
    ['G.6', 'ukg-positions-left-middle-right', 'Left, middle and right', 'position_left_middle_right', 10],
    ['G.7', 'ukg-positions-top-middle-bottom', 'Top, middle and bottom', 'position_top_middle_bottom', 10],
    ['G.8', 'ukg-positions-location-grid', 'Location in a grid', 'position_location_grid', 10],
  ]),
  ...chapter('Addition up to 5', [
    ['H.1', 'ukg-add5-pictures', 'Add with pictures - sums up to 5', 'addition_pictures', 5],
    ['H.2', 'ukg-add5-sentences', 'Addition sentences - sums up to 5', 'addition_sentences', 5],
    ['H.3', 'ukg-add5-make-number', 'Make a number using addition - sums up to 5', 'addition_make_number', 5],
    ['H.4', 'ukg-add5-add-two-numbers', 'Add two numbers - sums up to 5', 'addition_two_numbers', 5],
    ['H.5', 'ukg-add5-complete-sentence', 'Complete the addition sentence - sums up to 5', 'addition_complete_sentence', 5],
    ['H.6', 'ukg-add5-word-problems', 'Addition word problems - sums up to 5', 'addition_word_problems', 5],
  ]),
  ...chapter('Addition up to 10', [
    ['I.1', 'ukg-add10-pictures', 'Add with pictures - sums up to 10', 'addition_pictures', 10],
    ['I.2', 'ukg-add10-sentences', 'Addition sentences - sums up to 10', 'addition_sentences', 10],
    ['I.3', 'ukg-add10-make-number', 'Make a number using addition - sums up to 10', 'addition_make_number', 10],
    ['I.4', 'ukg-add10-add-two-numbers', 'Add two numbers - sums up to 10', 'addition_two_numbers', 10],
    ['I.5', 'ukg-add10-complete-sentence', 'Complete the addition sentence - sums up to 10', 'addition_complete_sentence', 10],
    ['I.6', 'ukg-add10-complete-make-10', 'Complete the addition sentence - make 10', 'addition_complete_make_10', 10],
    ['I.7', 'ukg-add10-write-sentences', 'Write addition sentences', 'addition_write_sentences', 10],
    ['I.8', 'ukg-add10-word-problems', 'Addition word problems - sums up to 10', 'addition_word_problems', 10],
  ]),
  ...chapter('Subtraction up to 5', [
    ['J.1', 'ukg-sub5-pictures', 'Subtract with pictures - numbers up to 5', 'subtraction_pictures', 5],
    ['J.2', 'ukg-sub5-sentences', 'Subtraction sentences - numbers up to 5', 'subtraction_sentences', 5],
    ['J.3', 'ukg-sub5-subtract', 'Subtract - numbers up to 5', 'subtraction_two_numbers', 5],
    ['J.4', 'ukg-sub5-complete-sentence', 'Complete the subtraction sentence - numbers up to 5', 'subtraction_complete_sentence', 5],
    ['J.5', 'ukg-sub5-word-problems', 'Subtraction word problems - numbers up to 5', 'subtraction_word_problems', 5],
  ]),
  ...chapter('Subtraction up to 10', [
    ['K.1', 'ukg-sub10-pictures', 'Subtract with pictures - numbers up to 10', 'subtraction_pictures', 10],
    ['K.2', 'ukg-sub10-sentences', 'Subtraction sentences - numbers up to 10', 'subtraction_sentences', 10],
    ['K.3', 'ukg-sub10-make-number', 'Make a number using subtraction - numbers up to 10', 'subtraction_make_number', 10],
    ['K.4', 'ukg-sub10-subtract', 'Subtract - numbers up to 10', 'subtraction_two_numbers', 10],
    ['K.5', 'ukg-sub10-complete-sentence', 'Complete the subtraction sentence - numbers up to 10', 'subtraction_complete_sentence', 10],
    ['K.6', 'ukg-sub10-write-sentences', 'Write subtraction sentences', 'subtraction_write_sentences', 10],
    ['K.7', 'ukg-sub10-word-problems', 'Subtraction word problems - numbers up to 10', 'subtraction_word_problems', 10],
  ]),
  ...chapter('Place shadow', [
    ['S.1', 'ukg-numbers-shadow-match', 'Sticker shadow matching', 'shadow_match', 3],
  ]),
  ...chapter('Classifying, sorting and ordering', [
    ['L.1', 'ukg-classify-same', 'Same', 'same', 10],
    ['L.2', 'ukg-classify-different', 'Different', 'different', 10],
    ['L.3', 'ukg-classify-same-different', 'Same and different', 'same_different', 10],
    ['L.4', 'ukg-classify-shapes-color', 'Classify shapes by colour', 'shapes_color', 10],
    ['L.5', 'ukg-classify-sort-color', 'Classify and sort by colour', 'sort_color', 10],
    ['L.6', 'ukg-classify-sort-shape', 'Classify and sort by shape', 'sort_shape', 10],
    ['L.7', 'ukg-classify-sort', 'Classify and sort', 'classify_sort', 10],
    ['L.8', 'ukg-venn-diagram-sort', 'Sort shapes into a Venn diagram', 'venn_sort', 10],
    ['L.9', 'ukg-venn-diagram-count', 'Count shapes in a Venn diagram', 'venn_count', 10],
    ['L.10', 'ukg-order-numbers-10', 'Put numbers up to 10 in order', 'order_numbers_10', 10],
    ['L.11', 'ukg-order-numbers-20', 'Put numbers up to 20 in order', 'order_numbers_20', 20],
  ]),
  ...chapter('Data and graphs', [
    ['M.1', 'ukg-pictograph-correct', 'Which pictograph is correct?', 'pictograph_correct', 10],
    ['M.2', 'ukg-pictograph-read', 'Read a pictograph', 'pictograph_read', 10],
  ]),
  ...chapter('Probability', [
    ['N.1', 'ukg-probability-likely', 'More or less likely', 'probability_likely', 10],
  ]),
  ...chapter('Measurement', [
    ['O.1', 'ukg-size-long-short', 'Long and short', 'size_long_short', 10],
    ['O.2', 'ukg-size-tall-short', 'Tall and short', 'size_tall_short', 10],
    ['O.3', 'ukg-size-wide-narrow', 'Wide and narrow', 'size_wide_narrow', 10],
    ['O.4', 'ukg-size-light-heavy', 'Light and heavy', 'size_light_heavy', 10],
  ]),
  ...chapter('Money', [
    ['P.1', 'ukg-money-coin-values', 'Coin values', 'money_coin_values', 10],
    ['P.2', 'ukg-money-count-1', 'Count money - 1-rupee coins only', 'money_count_1', 10],
    ['P.3', 'ukg-money-count-1-2', 'Count money - 1- and 2-rupee coins', 'money_count_1_2', 10],
    ['P.4', 'ukg-money-count-1-2-5', 'Count money - 1-, 2- and 5-rupee coins', 'money_count_1_2_5', 10],
    ['P.5', 'ukg-money-equivalent-groups', 'Equivalent groups of coins', 'money_equivalent_groups', 10],
    ['P.6', 'ukg-money-compare-groups', 'Compare two groups of coins', 'money_compare_groups', 10],
  ]),
];

export const ukgNumbersCountingSkillsByChapter = ukgNumbersCountingSkills.reduce((chapters, skill) => {
  chapters[skill.chapter] = [...(chapters[skill.chapter] || []), skill];
  return chapters;
}, {});

export const ukgNumbersCountingSkillMap = Object.fromEntries(
  ukgNumbersCountingSkills.map((skill) => [skill.skillId, skill])
);
