/**
 * Measurement Atomic Skills Catalog
 */

export const MEASUREMENT_CATALOG = [
  // --- Pre-K ---
  {
    skillId: 'meas-prek-long-short',
    grade: 'Pre-K',
    code: 'M.PK1',
    title: 'Compare long and short objects',
    description: 'Determine which of two horizontal objects is longer or shorter.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-k-long-short'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: '2D SVG objects',
    difficultyLevels: [1],
    misconceptions: ['not_aligning_zero'],
    remediationPrompt: 'Lined up side-by-side, the longer object sticks out further.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-prek-tall-short',
    grade: 'Pre-K',
    code: 'M.PK2',
    title: 'Compare tall and short objects',
    description: 'Determine which of two vertical objects is taller or shorter.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-k-tall-short'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: '2D SVG objects',
    difficultyLevels: [1],
    misconceptions: [],
    remediationPrompt: 'Look at which object extends higher from the ground.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-prek-light-heavy',
    grade: 'Pre-K',
    code: 'M.PK3',
    title: 'Compare light and heavy objects',
    description: 'Determine which object is heavier or lighter using balance scale visuals.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-k-light-heavy'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'balance scale',
    difficultyLevels: [1],
    misconceptions: ['large_is_heavy'],
    remediationPrompt: 'The heavier object tilts the balance scale down.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-prek-holds-more-less',
    grade: 'Pre-K',
    code: 'M.PK4',
    title: 'Compare holds more or less',
    description: 'Determine which container has greater or lesser volume capacity.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-k-holds-more-less'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'measuring cup',
    difficultyLevels: [1],
    misconceptions: ['tall_is_more'],
    remediationPrompt: 'The larger cup or bottle can hold more liquid.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },

  // --- Kindergarten ---
  {
    skillId: 'meas-k-long-short',
    grade: 'Kindergarten',
    code: 'M.K1',
    title: 'Compare long and short objects (K)',
    description: 'Kindergarten level comparison of horizontal lengths.',
    prerequisiteSkills: ['meas-prek-long-short'],
    relatedSkills: ['meas-g1-long-short'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: '2D SVG objects',
    difficultyLevels: [1],
    misconceptions: ['not_aligning_zero'],
    remediationPrompt: 'Align them at the same starting line to see which is longer.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-k-tall-short',
    grade: 'Kindergarten',
    code: 'M.K2',
    title: 'Compare tall and short objects (K)',
    description: 'Kindergarten level comparison of vertical heights.',
    prerequisiteSkills: ['meas-prek-tall-short'],
    relatedSkills: ['meas-g1-tall-short'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: '2D SVG objects',
    difficultyLevels: [1],
    misconceptions: [],
    remediationPrompt: 'Look at the top of each item when they stand on the same line.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-k-wide-narrow',
    grade: 'Kindergarten',
    code: 'M.K3',
    title: 'Wide and narrow',
    description: 'Identify which object or opening is wider or narrower.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g1-wide-narrow'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: '2D SVG objects',
    difficultyLevels: [1],
    misconceptions: [],
    remediationPrompt: 'Width is the horizontal opening. A wider path has more space.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-k-light-heavy',
    grade: 'Kindergarten',
    code: 'M.K4',
    title: 'Light and heavy (K)',
    description: 'Compare weights of objects on a balance scale.',
    prerequisiteSkills: ['meas-prek-light-heavy'],
    relatedSkills: ['meas-g1-light-heavy'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'balance scale',
    difficultyLevels: [1],
    misconceptions: ['large_is_heavy'],
    remediationPrompt: 'Heavy objects push down, light objects go up.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-k-holds-more-less',
    grade: 'Kindergarten',
    code: 'M.K5',
    title: 'Holds more or less (K)',
    description: 'Compare capacity volume sizes.',
    prerequisiteSkills: ['meas-prek-holds-more-less'],
    relatedSkills: ['meas-g1-holds-more-less'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'measuring cup',
    difficultyLevels: [1],
    misconceptions: ['tall_is_more'],
    remediationPrompt: 'Compare total container volumes.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-k-compare-mixed',
    grade: 'Kindergarten',
    code: 'M.K6',
    title: 'Compare size, weight, and capacity',
    description: 'Evaluate mixed measurable attributes.',
    prerequisiteSkills: ['meas-k-long-short', 'meas-k-light-heavy', 'meas-k-holds-more-less'],
    relatedSkills: ['meas-g1-compare-mixed'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'mixed',
    difficultyLevels: [2],
    misconceptions: ['large_is_heavy', 'tall_is_more'],
    remediationPrompt: 'Identify if the question asks for length, weight, or capacity.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },

  // --- Grade 1 ---
  {
    skillId: 'meas-g1-covers-more-less',
    grade: '1',
    code: 'M.1.1',
    title: 'Covers more or less',
    description: 'Introduction to area by comparing surface coverings.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g3-area-unit-squares'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: '2D SVG objects',
    difficultyLevels: [2],
    misconceptions: [],
    remediationPrompt: 'Area is the flat surface covered. Larger surfaces cover more.',
    templateName: 'meas.compare.size',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-g1-should-measure',
    grade: '1',
    code: 'M.1.2',
    title: 'Should you measure size, weight, or capacity?',
    description: 'Identify the appropriate physical attribute to measure for a scenario.',
    prerequisiteSkills: ['meas-k-compare-mixed'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'mixed',
    difficultyLevels: [2],
    misconceptions: [],
    remediationPrompt: 'Length/size is distance, weight is heaviness, capacity is container volume.',
    templateName: 'meas.choose.unit',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-g1-measure-objects',
    grade: '1',
    code: 'M.1.3',
    title: 'Measure length with objects',
    description: 'Measure items end-to-end using paperclips or pennies.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g1-measure-cubes-length'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'cube train',
    difficultyLevels: [2],
    misconceptions: ['leaving_gaps', 'overlapping_units'],
    remediationPrompt: 'Count all items from the start to the end with no gaps.',
    templateName: 'meas.nonstandard',
    engineName: 'nonStandardUnits'
  },
  {
    skillId: 'meas-g1-measure-cubes-length',
    grade: '1',
    code: 'M.1.4',
    title: 'Measure length with cubes',
    description: 'Measure horizontal items using a pre-laid cube train.',
    prerequisiteSkills: ['meas-g1-measure-objects'],
    relatedSkills: ['meas-g1-cube-trains-length'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'cube train',
    difficultyLevels: [2],
    misconceptions: ['leaving_gaps', 'overlapping_units'],
    remediationPrompt: 'Count the interlocking blocks aligned next to the object.',
    templateName: 'meas.nonstandard',
    engineName: 'nonStandardUnits'
  },
  {
    skillId: 'meas-g1-cube-trains-length',
    grade: '1',
    code: 'M.1.5',
    title: 'Build cube trains to measure length',
    description: 'Measure length using unit blocks.',
    prerequisiteSkills: ['meas-g1-measure-cubes-length'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'cube train',
    difficultyLevels: [2],
    misconceptions: [],
    remediationPrompt: 'Add cubes until the train matches the exact end of the object.',
    templateName: 'meas.nonstandard',
    engineName: 'nonStandardUnits'
  },
  {
    skillId: 'meas-g1-balance-compare',
    grade: '1',
    code: 'M.1.13',
    title: 'Compare weights on a balance scale',
    description: 'Determine which object or side is heavier or lighter on a balance scale.',
    prerequisiteSkills: ['meas-k-light-heavy'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'balance scale',
    difficultyLevels: [2],
    misconceptions: ['large_is_heavy'],
    remediationPrompt: 'Compare the weights of Box A and Box B. The heavier side tilts down.',
    templateName: 'meas.balance.compare',
    engineName: 'balanceScale'
  },
  {
    skillId: 'meas-g1-dice-interactive',
    grade: '1',
    code: 'M.1.14',
    title: 'Measure length with dice (interactive)',
    description: 'Measure horizontal lines by placing unit dice and counting them.',
    prerequisiteSkills: ['meas-g1-measure-cubes-length'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'dice interactive',
    difficultyLevels: [2],
    misconceptions: ['leaving_gaps', 'overlapping_units'],
    remediationPrompt: 'Click the "+" or the dice in the tray to place them under the line end-to-end.',
    templateName: 'meas.dice.interactive',
    engineName: 'diceMeasurement'
  },
  {
    skillId: 'meas-g1-dice-vertical',
    grade: '1',
    code: 'M.1.15',
    title: 'Measure height with dice (interactive)',
    description: 'Measure vertical heights of objects by placing unit dice and counting them.',
    prerequisiteSkills: ['meas-g1-dice-interactive'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'dice interactive',
    difficultyLevels: [2],
    misconceptions: ['leaving_gaps', 'overlapping_units'],
    remediationPrompt: 'Click or drag dice next to the object starting from the ground up.',
    templateName: 'meas.dice.vertical',
    engineName: 'diceMeasurement'
  },
  {
    skillId: 'meas-g1-measure-length-objects',
    grade: '1',
    code: 'M.1.16',
    title: 'Measure length with objects (NEW)',
    description: 'Measure horizontal lengths of objects by counting pre-placed units.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'nonstandard units',
    difficultyLevels: [2],
    misconceptions: ['starts_not_aligned', 'gap_between_units', 'overlap_units'],
    remediationPrompt: 'Count all units lined up end-to-end with no gaps or overlaps.',
    templateName: 'meas.nonstandard.multi',
    engineName: 'nonStandardUnitMeasurement',
    config: {
      layoutMode: 'horizontal_row',
      answerMode: 'count'
    }
  },
  {
    skillId: 'meas-g1-measure-height-objects',
    grade: '1',
    code: 'M.1.17',
    title: 'Measure height with objects (NEW)',
    description: 'Measure vertical heights of objects by counting pre-placed units.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'nonstandard units',
    difficultyLevels: [2],
    misconceptions: ['starts_not_aligned', 'gap_between_units', 'overlap_units'],
    remediationPrompt: 'Count all units stacked next to the object from bottom to top.',
    templateName: 'meas.nonstandard.multi',
    engineName: 'nonStandardUnitMeasurement',
    config: {
      layoutMode: 'vertical_stack',
      answerMode: 'count'
    }
  },
  {
    skillId: 'meas-g1-build-unit-trains-length',
    grade: '1',
    code: 'M.1.18',
    title: 'Build block trains to measure length (NEW)',
    description: 'Interactive drag/snap units horizontally to measure an object.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'nonstandard units interactive',
    difficultyLevels: [2],
    misconceptions: ['starts_not_aligned', 'gap_between_units', 'overlap_units'],
    remediationPrompt: 'Click or drag blocks next to the object to align them end-to-end.',
    templateName: 'meas.nonstandard.multi',
    engineName: 'nonStandardUnitMeasurement',
    config: {
      layoutMode: 'drag_to_measure',
      orientation: 'horizontal',
      answerMode: 'count'
    }
  },
  {
    skillId: 'meas-g1-build-unit-trains-height',
    grade: '1',
    code: 'M.1.19',
    title: 'Build block trains to measure height (NEW)',
    description: 'Interactive drag/snap units vertically to measure an object.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'nonstandard units interactive',
    difficultyLevels: [2],
    misconceptions: ['starts_not_aligned', 'gap_between_units', 'overlap_units', 'wrong_orientation'],
    remediationPrompt: 'Click or drag blocks next to the object from bottom to top.',
    templateName: 'meas.nonstandard.multi',
    engineName: 'nonStandardUnitMeasurement',
    config: {
      layoutMode: 'drag_to_measure',
      orientation: 'vertical',
      answerMode: 'count'
    }
  },
  {
    skillId: 'meas-g1-compare-measured-lengths',
    grade: '1',
    code: 'M.1.20',
    title: 'Compare measured lengths and heights (NEW)',
    description: 'Compare the sizes of two objects measured with non-standard units.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'nonstandard units comparison',
    difficultyLevels: [2],
    misconceptions: ['starts_not_aligned', 'counts_object_not_units'],
    remediationPrompt: 'Count the units for both items. The taller/longer one takes more units.',
    templateName: 'meas.nonstandard.multi',
    engineName: 'nonStandardUnitMeasurement',
    config: {
      layoutMode: 'compare_two_objects',
      answerMode: 'compare'
    }
  },
  {
    skillId: 'meas-g1-identify-measurement-errors',
    grade: '1',
    code: 'M.1.21',
    title: 'Identify measurement errors (NEW)',
    description: 'Spot correct or incorrect ways of measuring using blocks.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'nonstandard units error-spotting',
    difficultyLevels: [2],
    misconceptions: ['starts_not_aligned', 'gap_between_units', 'overlap_units'],
    remediationPrompt: 'Look for gaps, overlaps, or offset starting points.',
    templateName: 'meas.nonstandard.multi',
    engineName: 'nonStandardUnitMeasurement',
    config: {
      layoutMode: 'wrong_measure_fix',
      answerMode: 'error_type'
    }
  },

  // --- Grade 2 ---
  {
    skillId: 'meas-g2-indirect-comparison',
    grade: '2',
    code: 'M.2.1',
    title: 'Indirect comparison',
    description: 'Apply the transitive property (A > B and B > C => A > C) to compare lengths.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'none',
    difficultyLevels: [3],
    misconceptions: [],
    remediationPrompt: 'Order the items from longest to shortest based on the clues.',
    templateName: 'meas.choose.unit',
    engineName: 'compareSize'
  },
  {
    skillId: 'meas-g2-inch-ruler',
    grade: '2',
    code: 'M.2.2',
    title: 'Measure using an inch ruler',
    description: 'Measure objects to the nearest whole inch.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g3-inch-ruler'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'rulers',
    difficultyLevels: [2],
    misconceptions: ['not_aligning_zero'],
    remediationPrompt: 'Align the start of the object with the 0 mark on the ruler.',
    templateName: 'meas.ruler.reading',
    engineName: 'rulerReading'
  },
  {
    skillId: 'meas-g2-cm-ruler',
    grade: '2',
    code: 'M.2.3',
    title: 'Measure using a centimeter ruler',
    description: 'Measure objects to the nearest whole centimeter.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g3-estimate-cm-meters'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'rulers',
    difficultyLevels: [2],
    misconceptions: ['not_aligning_zero'],
    remediationPrompt: 'Align the start with 0 and read the end number.',
    templateName: 'meas.ruler.reading',
    engineName: 'rulerReading'
  },
  {
    skillId: 'meas-g2-balance-add',
    grade: '2',
    code: 'M.2.14',
    title: 'Balance scales: find weight to add',
    description: 'Calculate how much weight must be added to a scale to make it balance.',
    prerequisiteSkills: ['meas-g1-balance-compare'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'balance scale',
    difficultyLevels: [2, 3],
    misconceptions: [],
    remediationPrompt: 'Find the weight on each side. Subtract the lighter weight from the heavier weight.',
    templateName: 'meas.balance.add',
    engineName: 'balanceScale'
  },
  {
    skillId: 'meas-g2-balance-remove',
    grade: '2',
    code: 'M.2.15',
    title: 'Balance scales: find weight to remove',
    description: 'Calculate how much weight must be removed from a scale to make it balance.',
    prerequisiteSkills: ['meas-g1-balance-compare'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'balance scale',
    difficultyLevels: [2, 3],
    misconceptions: [],
    remediationPrompt: 'Find the weight on each side. Subtract the lighter weight from the heavier weight to find the excess.',
    templateName: 'meas.balance.remove',
    engineName: 'balanceScale'
  },
  {
    skillId: 'meas-g2-balance-interactive',
    grade: '2',
    code: 'M.2.16',
    title: 'Balance scales: interact to balance',
    description: 'Enter the weight needed to balance the scale and watch it adjust in real-time.',
    prerequisiteSkills: ['meas-g2-balance-add'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'balance scale',
    difficultyLevels: [2],
    misconceptions: [],
    remediationPrompt: 'Look at the target weight on the right side. Enter that same weight value to make it balance.',
    templateName: 'meas.balance.interactive',
    engineName: 'balanceScale'
  },

  // --- Grade 3 ---
  {
    skillId: 'meas-g3-inch-ruler',
    grade: '3',
    code: 'M.3.1',
    title: 'Measure using an inch ruler (half/quarter)',
    description: 'Measure to the nearest half or quarter inch.',
    prerequisiteSkills: ['meas-g2-inch-ruler'],
    relatedSkills: ['meas-g3-compare-inch-ruler'],
    crossTopicLinks: ['fractions'],
    questionTypes: ['fill in the blank'],
    visualType: 'rulers',
    difficultyLevels: [3],
    misconceptions: ['fraction_scale_confusion', 'counting_ticks_incorrectly'],
    remediationPrompt: 'Count half inches and quarter inches from the last whole number.',
    templateName: 'meas.ruler.reading',
    engineName: 'rulerReading'
  },
  {
    skillId: 'meas-g3-compare-inch-ruler',
    grade: '3',
    code: 'M.3.2',
    title: 'Measure to compare length in inches',
    description: 'Measure two items on rulers and calculate the difference.',
    prerequisiteSkills: ['meas-g3-inch-ruler'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'rulers',
    difficultyLevels: [3],
    misconceptions: [],
    remediationPrompt: 'Find the length of both items, then subtract.',
    templateName: 'meas.ruler.compare',
    engineName: 'rulerReading'
  },
  {
    skillId: 'meas-g3-choose-tool',
    grade: '3',
    code: 'M.3.3',
    title: 'Choose the best measuring tool',
    description: 'Select between scales, rulers, cups, and thermometers.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g4-choose-tool'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'real-world objects',
    difficultyLevels: [2],
    misconceptions: [],
    remediationPrompt: 'Match the tool to what it measures.',
    templateName: 'meas.choose.tool',
    engineName: 'chooseTool'
  },
  {
    skillId: 'meas-g3-area-unit-squares',
    grade: '3',
    code: 'M.3.4',
    title: 'Find area using unit squares',
    description: 'Count grid unit squares to determine surface area.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: ['geometry'],
    questionTypes: ['fill in the blank'],
    visualType: 'unit squares',
    difficultyLevels: [2],
    misconceptions: [],
    remediationPrompt: 'Count every shaded grid block to find the total square units.',
    templateName: 'meas.nonstandard',
    engineName: 'nonStandardUnits'
  },
  {
    skillId: 'meas-g3-fahrenheit-thermometer',
    grade: '3',
    code: 'M.3.5',
    title: 'Read a Fahrenheit thermometer',
    description: 'Determine the temperature reading, handling 2-degree ticks.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g3-celsius-thermometer'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'thermometers',
    difficultyLevels: [3],
    misconceptions: ['tick_scale_multiplier'],
    remediationPrompt: 'Look closely at the ticks. Each subdivision line represents 2 degrees.',
    templateName: 'meas.thermometer',
    engineName: 'thermometer'
  },
  {
    skillId: 'meas-g3-celsius-thermometer',
    grade: '3',
    code: 'M.3.6',
    title: 'Read a Celsius thermometer',
    description: 'Read Celsius temperatures with 1-degree tick increments.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g3-fahrenheit-thermometer'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'thermometers',
    difficultyLevels: [3],
    misconceptions: [],
    remediationPrompt: 'Read the temperature line in Celsius (°C).',
    templateName: 'meas.thermometer',
    engineName: 'thermometer'
  },
  {
    skillId: 'meas-g3-liquid-volume',
    grade: '3',
    code: 'M.3.7',
    title: 'Measure liquid volumes',
    description: 'Read fluids in graduated cylinders or measuring cups.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'measuring cups',
    difficultyLevels: [3],
    misconceptions: [],
    remediationPrompt: 'Read the level of the line where the top of the water reaches.',
    templateName: 'meas.liquid.volume',
    engineName: 'liquidVolume'
  },

  // --- Grade 4 ---
  {
    skillId: 'meas-g4-customary-conversion-tables',
    grade: '4',
    code: 'M.4.1',
    title: 'Customary conversion tables',
    description: 'Fill in missing values in feet-to-inches or gallon-to-quart tables.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-g4-convert-customary'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'conversion tables',
    difficultyLevels: [3],
    misconceptions: ['base_10_bias'],
    remediationPrompt: 'Use conversion rules: 1 foot = 12 inches. Multiply to convert.',
    templateName: 'meas.conversion.table',
    engineName: 'unitConversion'
  },
  {
    skillId: 'meas-g4-add-sub-mixed-customary',
    grade: '4',
    code: 'M.4.2',
    title: 'Add and subtract mixed customary units',
    description: 'Add or subtract dimensions (e.g. feet and inches) requiring regrouping.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: ['base_10_bias'],
    remediationPrompt: 'Remember that 12 inches equals 1 foot, not 10! Carry over accordingly.',
    templateName: 'meas.conversion.mixed',
    engineName: 'mixedUnits'
  },

  // --- Grade 5 ---
  {
    skillId: 'meas-g5-cm-ruler',
    grade: '5',
    code: 'M.5.1',
    title: 'Measure using a centimeter ruler (decimals)',
    description: 'Measure to the nearest millimeter or decimal centimeter.',
    prerequisiteSkills: ['meas-g2-cm-ruler'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'rulers',
    difficultyLevels: [3],
    misconceptions: [],
    remediationPrompt: 'Count small millimeter ticks. Each is 0.1 cm.',
    templateName: 'meas.ruler.reading',
    engineName: 'rulerReading'
  },
  {
    skillId: 'meas-g5-multistep-customary',
    grade: '5',
    code: 'M.5.2',
    title: 'Multi-step customary conversions',
    description: 'Perform chain conversions (e.g. yards to inches).',
    prerequisiteSkills: ['meas-g4-customary-conversion-tables'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [5],
    misconceptions: [],
    remediationPrompt: 'First convert to intermediate units (e.g. yards to feet, then feet to inches).',
    templateName: 'meas.conversion.single',
    engineName: 'unitConversion'
  },

  // --- Grade 6 ---
  {
    skillId: 'meas-g6-convert-customary-metric',
    grade: '6',
    code: 'M.6.1',
    title: 'Convert between customary and metric systems',
    description: 'Approximate system cross-conversions.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [5],
    misconceptions: [],
    remediationPrompt: 'Multiply the input by the approximate conversion factor.',
    templateName: 'meas.conversion.single',
    engineName: 'unitConversion'
  },
  {
    skillId: 'meas-g6-convert-celsius-fahrenheit',
    grade: '6',
    code: 'M.6.2',
    title: 'Convert Celsius and Fahrenheit',
    description: 'Convert temperatures using equations.',
    prerequisiteSkills: ['meas-g3-fahrenheit-thermometer'],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: [],
    remediationPrompt: 'Use F = (9/5)C + 32 or C = (F - 32) * 5/9.',
    templateName: 'meas.conversion.single',
    engineName: 'unitConversion'
  },

  // --- Grade 7 ---
  {
    skillId: 'meas-g7-unit-prices-conversions',
    grade: '7',
    code: 'M.7.1',
    title: 'Unit prices with unit conversions',
    description: 'Compare item unit prices involving conversions.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: ['ratio'],
    questionTypes: ['mcq'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: [],
    remediationPrompt: 'Convert them to the same units first before comparing prices.',
    templateName: 'meas.wordproblems',
    engineName: 'unitConversion'
  },

  // --- Grade 8 ---
  {
    skillId: 'meas-g8-convert-rates',
    grade: '8',
    code: 'M.8.1',
    title: 'Convert rates and measurements',
    description: 'Convert composite rates (e.g. speed mph to ft/s).',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: ['ratio'],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [5],
    misconceptions: [],
    remediationPrompt: 'Use dimensional analysis. Convert distance and time individually.',
    templateName: 'meas.conversion.single',
    engineName: 'unitConversion'
  },

  // --- Algebra 1 ---
  {
    skillId: 'meas-alg1-precision',
    grade: 'Algebra 1',
    code: 'M.A1',
    title: 'Precision in measurement',
    description: 'Determine which tool or value is more precise based on increments.',
    prerequisiteSkills: [],
    relatedSkills: ['meas-alg1-greatest-possible-error'],
    crossTopicLinks: [],
    questionTypes: ['mcq'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: [],
    remediationPrompt: 'The tool with the smallest scale unit is the most precise.',
    templateName: 'meas.precision.error',
    engineName: 'precisionError'
  },
  {
    skillId: 'meas-alg1-greatest-possible-error',
    grade: 'Algebra 1',
    code: 'M.A2',
    title: 'Greatest possible error',
    description: 'Calculate greatest possible error (GPE) from measurement values.',
    prerequisiteSkills: ['meas-alg1-precision'],
    relatedSkills: ['meas-alg1-percent-error'],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: [],
    remediationPrompt: 'GPE is always exactly half of the precision increment.',
    templateName: 'meas.precision.error',
    engineName: 'precisionError'
  },
  {
    skillId: 'meas-alg1-percent-error',
    grade: 'Algebra 1',
    code: 'M.A3',
    title: 'Percent error',
    description: 'Determine percentage deviation from the actual measurement.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: [],
    remediationPrompt: 'Percent error is (Absolute Error / Actual Value) * 100.',
    templateName: 'meas.precision.error',
    engineName: 'precisionError'
  },

  // --- Geometry ---
  {
    skillId: 'meas-geom-convert-square-cubic',
    grade: 'Geometry',
    code: 'M.G1',
    title: 'Convert square and cubic units',
    description: 'Convert areas and volumes between different units.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: ['geometry'],
    questionTypes: ['fill in the blank'],
    visualType: '3D cubes/prisms',
    difficultyLevels: [5],
    misconceptions: ['square_cubic_linear_bias'],
    remediationPrompt: 'Remember to square the factor for area, and cube it for volume.',
    templateName: 'meas.conversion.single',
    engineName: 'unitConversion'
  },

  // --- Advanced / Science-Based ---
  {
    skillId: 'meas-adv-density-mass-volume',
    grade: 'Advanced',
    code: 'M.ADV1',
    title: 'Calculate density, mass, and volume',
    description: 'Apply ratios to compute physical density.',
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: ['ratio'],
    questionTypes: ['fill in the blank'],
    visualType: 'none',
    difficultyLevels: [4],
    misconceptions: [],
    remediationPrompt: 'Density = Mass / Volume. Mass = Density * Volume. Volume = Mass / Density.',
    templateName: 'meas.density',
    engineName: 'density'
  },

  // --- SVG Tools Demo Chapter ---
  ...[
    ['meas-svg-inch-ruler', 'SVG.1', 'SVG demo: inch ruler', 'inch_ruler'],
    ['meas-svg-centimeter-ruler', 'SVG.2', 'SVG demo: centimeter ruler', 'centimeter_ruler'],
    ['meas-svg-measuring-tape', 'SVG.3', 'SVG demo: measuring tape', 'measuring_tape'],
    ['meas-svg-protractor', 'SVG.4', 'SVG demo: protractor', 'protractor'],
    ['meas-svg-compass', 'SVG.5', 'SVG demo: compass', 'compass'],
    ['meas-svg-thermometer', 'SVG.6', 'SVG demo: thermometer', 'thermometer'],
    ['meas-svg-balance-scale', 'SVG.7', 'SVG demo: balance scale', 'balance_scale'],
    ['meas-svg-measuring-cup', 'SVG.8', 'SVG demo: measuring cup', 'measuring_cup'],
    ['meas-svg-stopwatch', 'SVG.9', 'SVG demo: stopwatch', 'stopwatch'],
    ['meas-svg-number-line', 'SVG.10', 'SVG demo: number line', 'number_line'],
    ['meas-svg-liter-jug', 'SVG.11', 'SVG demo: liter jug', 'liter_jug'],
    ['meas-svg-graduated-cylinder', 'SVG.12', 'SVG demo: graduated cylinder', 'graduated_cylinder'],
    ['meas-svg-beaker', 'SVG.13', 'SVG demo: beaker', 'beaker']
  ].map(([skillId, code, title, toolId]) => ({
    skillId,
    grade: 'SVG Tools Demo',
    code,
    title,
    description: `Dynamic question demo for the shared SVG tool registry item: ${toolId}.`,
    prerequisiteSkills: [],
    relatedSkills: [],
    crossTopicLinks: [],
    questionTypes: ['fill in the blank'],
    visualType: 'dynamic SVG tool',
    difficultyLevels: [1],
    misconceptions: [],
    remediationPrompt: 'Read the highlighted value shown by the SVG tool.',
    templateName: 'meas.svg.tool.demo',
    engineName: 'svgToolDemo',
    config: {
      toolId,
      forcedTask: `svg_tool_demo_${toolId}`
    }
  }))
];

export function getMeasurementSkill(skillId) {
  return MEASUREMENT_CATALOG.find(s => s.skillId === skillId || s.code === skillId) || null;
}
