const adaptiveDifficulty = {
  easy: { digits: [4, 5], visual: true, guided: true },
  medium: { digits: [6, 7], visual: true, guided: false },
  hard: { digits: [8, 9], visual: false, guided: false },
};

const remediation = (prerequisiteSkills = [], hintStrategy = []) => ({
  prerequisiteSkills,
  scaffoldLevels: ['visual', 'guided', 'independent'],
  hintStrategy,
});

export const grade5PlaceValueSkills = [
  {
    id: 'pv-g5-round-nearest-thousand',
    code: 'G5.PV.13',
    grade: 5,
    topic: 'place-values',
    competencyId: 'rounding_estimation',
    title: 'Round large numbers to the nearest thousand',
    templateId: 'place-values.rounding.nearest-thousand',
    engine: 'system',
    difficulty: adaptiveDifficulty,
    prerequisites: ['pv-g4-compare-large-numbers'],
    misconceptions: ['rounding_direction_error', 'midpoint_confusion', 'place_target_confusion'],
    remediation: remediation(['pv-g4-compare-large-numbers'], [
      'show_number_line',
      'mark_midpoint',
      'compare_distance_to_benchmarks',
    ]),
    config: { forcedTask: 'rounding_number_line', difficulty: 'medium' },
  },
  {
    id: 'pv-g5-round-nearest-lakh',
    code: 'G5.PV.14',
    grade: 5,
    topic: 'place-values',
    competencyId: 'rounding_estimation',
    title: 'Round large numbers to the nearest lakh',
    templateId: 'place-values.rounding.nearest-lakh',
    engine: 'system',
    difficulty: adaptiveDifficulty,
    prerequisites: ['pv-g4-indian-comma-placement', 'pv-g5-round-nearest-thousand'],
    misconceptions: ['rounding_direction_error', 'lakh_crore_reversal', 'place_target_confusion'],
    remediation: remediation(['pv-g5-round-nearest-thousand'], [
      'highlight_lakh_place',
      'show_number_line',
    ]),
    config: { forcedTask: 'rounding_nearest_lakh', difficulty: 'hard' },
  },
  {
    id: 'pv-g5-button-machine-decomposition',
    code: 'G5.PV.15',
    grade: 5,
    topic: 'place-values',
    competencyId: 'flexible_decomposition',
    title: 'Build numbers with place-value buttons',
    templateId: 'place-values.decomposition.button-machine',
    engine: 'system',
    difficulty: adaptiveDifficulty,
    prerequisites: ['pv-g4-expanded-form-large'],
    misconceptions: ['expanded_form_missing_zero', 'incorrect_regrouping'],
    remediation: remediation(['pv-g4-expanded-form-large'], [
      'count_minimal_button_clicks',
      'show_digit_to_button_mapping',
    ]),
    config: { forcedTask: 'button_machine_decomposition', difficulty: 'medium' },
  },
  {
    id: 'pv-g5-number-magnitude-benchmarks',
    code: 'G5.PV.16',
    grade: 5,
    topic: 'place-values',
    competencyId: 'large_number_magnitude',
    title: 'Choose the best benchmark for a large number',
    templateId: 'place-values.magnitude.benchmark',
    engine: 'system',
    difficulty: adaptiveDifficulty,
    prerequisites: ['pv-g4-order-large-numbers'],
    misconceptions: ['magnitude_underestimation', 'benchmark_mismatch'],
    remediation: remediation(['pv-g4-order-large-numbers'], [
      'show_magnitude_bars',
      'compare_with_real_world_quantities',
    ]),
    config: { forcedTask: 'magnitude_benchmark', difficulty: 'medium' },
  },
  {
    id: 'pv-g5-shortcut-multiply-10-100-1000',
    code: 'G5.PV.17',
    grade: 5,
    topic: 'place-values',
    competencyId: 'shortcut_scaling',
    title: 'Multiply by 10, 100, and 1,000 using place value',
    templateId: 'place-values.shortcut-multiplication',
    engine: 'system',
    difficulty: adaptiveDifficulty,
    prerequisites: ['pv-g4-expanded-form-large'],
    misconceptions: ['zero_append_without_place_value', 'digit_shift_confusion'],
    remediation: remediation(['pv-g4-expanded-form-large'], [
      'show_digit_shift_chart',
      'connect_multiplication_to_place_shift',
    ]),
    config: { forcedTask: 'shortcut_multiplication', difficulty: 'medium' },
  },
];
