// Centralized list of all practice generator template IDs, grouped topic-wise.
// Used in the Admin panel to select template IDs when creating/editing skills.

export const ALL_TEMPLATES_BY_TOPIC = {
  'addition': [
    { id: 'addition.numbers.horizontal', engine: 'addition', questionType: 'fillInTheBlank', title: 'Horizontal Numbers Addition' },
    { id: 'addition.numbers.vertical', engine: 'addition', questionType: 'fillInTheBlank', title: 'Vertical Numbers Addition' },
    { id: 'addition.numbers.threeAddendsTarget', engine: 'addition', questionType: 'fillInTheBlank', title: 'Three Addends Target Sum' },
    { id: 'addition.numbers.doublesPlusOne', engine: 'addition', questionType: 'fillInTheBlank', title: 'Doubles Plus One' },
    { id: 'addition.visual.counting', engine: 'addition', questionType: 'fillInTheBlank', title: 'Visual Counting (Cubes)' },
    { id: 'addition.visual.copyDice', engine: 'addition', questionType: 'categorization', title: 'Visual Copy Dice' },
    { id: 'addition.visual.modelMatch', engine: 'addition', questionType: 'mcq', title: 'Visual Model Match' },
    { id: 'addition.visual.pictureSentence', engine: 'addition', questionType: 'mcq', title: 'Visual Picture Sentence' },
    { id: 'addition.sort.factsTo20', engine: 'addition', questionType: 'categorization', title: 'Sort Facts to 20' },
    { id: 'addition.sort.valuesTo20Html', engine: 'addition', questionType: 'categorization', title: 'Sort Values to 20 (HTML)' },
    { id: 'addition.makeNumber.to20', engine: 'addition', questionType: 'mcq', title: 'Make Number to 20' },
    { id: 'addition.word.model.to20', engine: 'addition', questionType: 'mcq', title: 'Word Problem Model to 20' },
    { id: 'addition.word.sentence', engine: 'addition', questionType: 'fillInTheBlank', title: 'Word Problem Sentence' },
    { id: 'meas.nonstandard.multi', engine: 'addition', questionType: 'fillInTheBlank', title: 'Nonstandard Unit Measurement Sum' }
  ],
  'subtraction': [
    { id: 'subtraction.visual.removeCubes', engine: 'subtraction', questionType: 'fillInTheBlank', title: 'Visual Remove Cubes' },
    { id: 'subtraction.mcq.modelMatch', engine: 'subtraction', questionType: 'mcq', title: 'MCQ Model Match' },
    { id: 'subtraction.mcq.pictureSentence', engine: 'subtraction', questionType: 'mcq', title: 'MCQ Picture Sentence' }
  ],
  'multiplication': [
    { id: 'multiplication.facts.basic', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Basic Multiplication Facts' },
    { id: 'multiplication.vertical.1digit', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Vertical 1-digit' },
    { id: 'multiplication.vertical.2digit.by1digit', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Vertical 2-digit by 1-digit' },
    { id: 'multiplication.vertical.3digit.by1digit', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Vertical 3-digit by 1-digit' },
    { id: 'multiplication.vertical.4digit.by1digit', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Vertical 4-digit by 1-digit' },
    { id: 'multiplication.visual.equalGroups.describe', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Describe Equal Groups' },
    { id: 'multiplication.visual.equalGroups.expression', engine: 'multiplication', questionType: 'mcq', title: 'Match Expression to Equal Groups' },
    { id: 'multiplication.visual.equalGroups.sentence', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Sentence for Equal Groups' },
    { id: 'multiplication.visual.equalGroups.relateAddition', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Relate Addition to Equal Groups' },
    { id: 'multiplication.visual.equalGroups.rabbits', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Equal Groups of Rabbits' },
    { id: 'multiplication.visual.equalGroups.penguins', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Equal Groups of Penguins' },
    { id: 'multiplication.cubes.repeatedAddition', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Repeated Addition with Cubes' },
    { id: 'multiplication.cubes.arrays', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Multiplication Arrays with Cubes' },
    { id: 'multiplication.cubes.areaModel', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Area Modeling with Cubes' },
    { id: 'multiplication.cubes.distributiveProperty', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Distributive Property with Cubes' },
    { id: 'multiplication.cubes.areaGridRectangle', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Area Grid Rectangle with Cubes (Count)' },
    { id: 'multiplication.cubes.areaGridRectangleFill', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Area Grid Rectangle with Cubes (Fill)' },
    { id: 'multiplication.numberLine.identify', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Number Line Multiplication (Identify)' },
    { id: 'multiplication.numberLine.skipCount', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Number Line Multiplication (Skip Count)' },
    { id: 'multiplication.cubes.repeatedAdditionTower', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Repeated Addition Tower (Cubes)' },
    { id: 'multiplication.cubes.dotArray', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Dot Array Modeling' },
    { id: 'multiplication.barModel.findTotalSingle', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Bar Model Find Total' },
    { id: 'multiplication.barModel.findValueSingle', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Bar Model Find Part Value' },
    { id: 'multiplication.barModel.comparisonLarge', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Bar Model Multiplicative Comparison (Large)' },
    { id: 'multiplication.barModel.comparisonSmall', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Bar Model Multiplicative Comparison (Small)' },
    { id: 'multiplication.functionMachine.findOutput', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Function Machine Find Output' },
    { id: 'multiplication.functionMachine.findInput', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Function Machine Find Input' },
    { id: 'multiplication.functionMachine.findRule', engine: 'multiplication', questionType: 'fillInTheBlank', title: 'Function Machine Find Rule' }
  ],
  'fractions': [
    { id: 'fractions.identify.visual', engine: 'fractions', questionType: 'mcq', title: 'Identify Visual Fractions' },
    { id: 'fractions-g2-identify-visual', engine: 'fractions', questionType: 'mcq', title: 'Grade 2 Identify Visual' },
    { id: 'fractions.compare.likeUnlike', engine: 'fractions', questionType: 'mcq', title: 'Compare Like/Unlike Fractions' },
    { id: 'fractions.identify.likeFractions', engine: 'fractions', questionType: 'mcq', title: 'Identify Like Fractions' },
    { id: 'fractions.identify.unlikeFractions', engine: 'fractions', questionType: 'mcq', title: 'Identify Unlike Fractions' },
    { id: 'fractions-g3-like-unlike', engine: 'fractions', questionType: 'mcq', title: 'Grade 3 Like/Unlike' },
    { id: 'fractions.types.proper', engine: 'fractions', questionType: 'mcq', title: 'Proper Fractions' },
    { id: 'fractions.types.improper', engine: 'fractions', questionType: 'mcq', title: 'Improper Fractions' },
    { id: 'fractions.types.mixed', engine: 'fractions', questionType: 'mcq', title: 'Mixed Fractions' },
    { id: 'fractions.types.identify', engine: 'fractions', questionType: 'mcq', title: 'Identify Fractions Types' },
    { id: 'fractions-g3-types', engine: 'fractions', questionType: 'mcq', title: 'Grade 3 Types' },
    { id: 'fractions.conversion.improperToMixed', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Improper to Mixed' },
    { id: 'fractions-g5-convert-improper-to-mixed', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Improper to Mixed' },
    { id: 'fractions.conversion.mixedToImproper', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Mixed to Improper' },
    { id: 'fractions-g5-convert-mixed-to-improper', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Mixed to Improper' },
    { id: 'fractions.compare.likeFractions', engine: 'fractions', questionType: 'mcq', title: 'Compare Like Fractions' },
    { id: 'fractions-g5-compare-like-fractions', engine: 'fractions', questionType: 'mcq', title: 'Grade 5 Compare Like Fractions' },
    { id: 'fractions.compare.unlikeFractions', engine: 'fractions', questionType: 'mcq', title: 'Compare Unlike Fractions' },
    { id: 'fractions-g5-compare-unlike-fractions', engine: 'fractions', questionType: 'mcq', title: 'Grade 5 Compare Unlike' },
    { id: 'fractions.compare.properFractions', engine: 'fractions', questionType: 'mcq', title: 'Compare Proper Fractions' },
    { id: 'fractions-g5-compare-proper-fractions', engine: 'fractions', questionType: 'mcq', title: 'Grade 5 Compare Proper' },
    { id: 'fractions.addition.likeFractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Add Like Fractions' },
    { id: 'fractions-g5-add-like-fractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Add Like Fractions' },
    { id: 'fractions.addition.improperFractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Add Improper Fractions' },
    { id: 'fractions-g5-add-improper-fractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Add Improper' },
    { id: 'fractions.addition.fractionAndInteger', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Add Fraction and Integer' },
    { id: 'fractions-g5-add-fraction-and-integer', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Add Fraction & Integer' },
    { id: 'fractions.addition.missingFractionAddend', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Missing Fraction Addend' },
    { id: 'fractions-g5-missing-fraction-addend', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Missing Fraction Addend' },
    { id: 'fractions.addition.missingIntegerAddend', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Missing Integer Addend' },
    { id: 'fractions-g5-missing-integer-addend', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Missing Integer Addend' },
    { id: 'fractions.addition.multipleFractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Add Multiple Fractions' },
    { id: 'fractions-g5-add-multiple-fractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Add Multiple Fractions' },
    { id: 'fractions-g5-add-subtract-unlike-denominators', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Grade 5 Add/Subtract Unlike Denominators' },
    { id: 'fractions.unlikeDenominators.addSubtract', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Unlike Denominators Add/Subtract' },
    { id: 'visual_models_identify', engine: 'fractions', questionType: 'mcq', title: 'Identify Fraction from Shapes' },
    { id: 'visual_models_write_fraction', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Write Fraction from Shape' },
    { id: 'visual_models_equal_parts', engine: 'fractions', questionType: 'mcq', title: 'Equal vs Unequal Parts' },
    { id: 'visual_models_fraction_of_set', engine: 'fractions', questionType: 'mcq', title: 'Fraction of a Set' },
    { id: 'visual_models_mixed_numbers', engine: 'fractions', questionType: 'mcq', title: 'Mixed Numbers Visual' },
    { id: 'visual_models_remove_fraction_pie', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Remove Fraction (Pie)' },
    { id: 'visual_models_remove_fraction_square', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Remove Fraction (Square)' },
    { id: 'visual_models_remove_fraction_rectangle', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Remove Fraction (Rectangle)' },
    { id: 'visual_models_remove_fraction_bar', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Remove Fraction (Bar)' },
    { id: 'visual_models_fill_fraction_pie', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Fill Fraction (Pie)' },
    { id: 'visual_models_fill_fraction_square', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Fill Fraction (Square)' },
    { id: 'visual_models_fill_fraction_rectangle', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Fill Fraction (Rectangle)' },
    { id: 'visual_models_cut_rectangle_fourths', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Cut Rectangle into Fourths' },
    { id: 'visual_models_cut_circle_fourths', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Cut Circle into Fourths' },
    { id: 'visual_models_cut_rectangle_halves_different', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Cut halves in different ways' },
    { id: 'visual_models_cut_rectangle_thirds', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Cut Rectangle into Thirds' },
    { id: 'visual_models_cut_circle_thirds', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Cut Circle into Thirds' },
    { id: 'visual_models_cut_circle_sixths', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Cut Circle into Sixths' },
    { id: 'fractions_decompose_into_unit_fractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Decompose into Unit Fractions' },
    { id: 'fractions_decompose_missing_unit_fraction', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Decompose: Missing Piece' },
    { id: 'fractions_decompose_select_all_sums', engine: 'fractions', questionType: 'mcq', title: 'Decompose: Select all matches' },
    { id: 'fractions_build_from_words', engine: 'fractions', questionType: 'mcq', title: 'Build Fraction from Words' },
    { id: 'fractions_decompose_error_analysis', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Decompose: Error Analysis' },
    { id: 'fractions_count_unit_fraction_pieces', engine: 'fractions', questionType: 'mcq', title: 'Count Unit Fraction Pieces' },
    { id: 'fractions_decompose_puzzle_style', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Decompose Puzzle' },
    { id: 'number_lines_identify', engine: 'fractions', questionType: 'mcq', title: 'Identify Fraction on Number Line' },
    { id: 'number_lines_graph', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Graph Fraction on Number Line' },
    { id: 'equivalence_number_line', engine: 'fractions', questionType: 'mcq', title: 'Equivalent Fractions on Number Line' },
    { id: 'equivalence_simplify', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Simplify Fractions' },
    { id: 'equivalence_identify_equivalent', engine: 'fractions', questionType: 'mcq', title: 'Identify Equivalent Pairs' },
    { id: 'equivalence_missing_value', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Equivalent Missing Value' },
    { id: 'equivalence_patterns', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Equivalence Patterns' },
    { id: 'conversions_fraction_to_decimal', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Convert Fraction to Decimal' },
    { id: 'conversions_decimal_to_fraction_simple', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Convert Decimal to Fraction' },
    { id: 'conversions_decimal_to_mixed_standard', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Convert Decimal to Mixed (Std)' },
    { id: 'conversions_decimal_to_mixed_large', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Convert Decimal to Mixed (Large)' },
    { id: 'conversions_decimal_to_mixed_hundredths', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Convert Decimal to Mixed (Hundredths)' },
    { id: 'word_problems_fraction_model', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Word Problem: Fraction Model' },
    { id: 'word_problems_fraction_value', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Word Problem: Fraction Value' },
    { id: 'word_problems_fraction_of_set', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Word Problem: Fraction of Set' },
    { id: 'word_problems_fraction_of_number', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Word Problem: Fraction of Number' },
    { id: 'operations_add_like_denominators', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Add Like Denominators' },
    { id: 'operations_subtract_like_denominators', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Subtract Like Denominators' },
    { id: 'operations_fraction_of_number', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Multiply Fraction by Integer' },
    { id: 'comparison_visual_compare', engine: 'fractions', questionType: 'mcq', title: 'Compare Fractions Visually' },
    { id: 'comparison_sorting_fractions', engine: 'fractions', questionType: 'sorting', title: 'Sort Fractions' },
    { id: 'rational_numbers_add_sub', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Add/Sub Fractions' },
    { id: 'rational_numbers_add_sub_wp', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Add/Sub Word Problems' },
    { id: 'rational_numbers_compare', engine: 'fractions', questionType: 'mcq', title: 'Rational: Compare Numbers' },
    { id: 'rational_numbers_convert_decimals_fractions', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Decimals & Fractions' },
    { id: 'rational_numbers_convert_percents', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Convert Percents' },
    { id: 'rational_numbers_evaluate', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Evaluate Expressions' },
    { id: 'rational_numbers_mul_div', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Mul/Div Fractions' },
    { id: 'rational_numbers_mul_div_wp', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Mul/Div Word Problems' },
    { id: 'rational_numbers_powers', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Powers of Numbers' },
    { id: 'rational_numbers_order', engine: 'fractions', questionType: 'sorting', title: 'Rational: Order Numbers' },
    { id: 'rational_numbers_reciprocals', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Reciprocals' },
    { id: 'rational_numbers_round', engine: 'fractions', questionType: 'fillInTheBlank', title: 'Rational: Rounding' }
  ],
  'place-values': [
    { id: 'place-values.blocks.units', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Identify Blocks (Ones & Tens)' },
    { id: 'place-values.blocks.match-number', engine: 'place-values', questionType: 'mcq', title: 'Match Blocks to Number' },
    { id: 'place-values.blocks.hundreds', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Identify Blocks (Hundreds)' },
    { id: 'place-values.blocks.thousands', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Identify Blocks (Thousands)' },
    { id: 'place-values.place-name', engine: 'place-values', questionType: 'mcq', title: 'Identify Place Value Name' },
    { id: 'place-values.expanded-form', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Expanded Form (Standard)' },
    { id: 'place-values.word-to-number', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Word Name to Digits' },
    { id: 'place-values.breakdown-table', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Place Breakdown Table' },
    { id: 'place-values.comma.indian', engine: 'place-values', questionType: 'mcq', title: 'Indian Comma System' },
    { id: 'place-values.comma.international', engine: 'place-values', questionType: 'mcq', title: 'International Comma System' },
    { id: 'place-values.chart.large', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Indian Place Chart' },
    { id: 'place-values.expanded-form.large', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Expanded Form (Large numbers)' },
    { id: 'place-values.compare.large', engine: 'place-values', questionType: 'mcq', title: 'Compare Large Numbers' },
    { id: 'place-values.order.large', engine: 'place-values', questionType: 'mcq', title: 'Order Large Numbers' },
    { id: 'place-values.rounding.nearest-thousand', engine: 'place-values', questionType: 'mcq', title: 'Round to Nearest Thousand' },
    { id: 'place-values.rounding.nearest-lakh', engine: 'place-values', questionType: 'mcq', title: 'Round to Nearest Lakh' },
    { id: 'place-values.decomposition.button-machine', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Button Machine Decomposition' },
    { id: 'place-values.magnitude.benchmark', engine: 'place-values', questionType: 'mcq', title: 'Number Magnitude Benchmarks' },
    { id: 'place-values.shortcut-multiplication', engine: 'place-values', questionType: 'fillInTheBlank', title: 'Shortcut Multiplication (x10, x100)' },
    { id: 'place-values.system.conversion', engine: 'place-values', questionType: 'mcq', title: 'Convert Indian to International units' }
  ],
  'standard-object-measurement': [
    { id: 'som-g1-measure-length', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Measure horizontal length (Cubes)' },
    { id: 'som-g1-measure-height', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Measure vertical height (Dice)' },
    { id: 'som-g1-compare', engine: 'standard-object-measurement', questionType: 'mcq', title: 'Compare object lengths (Paperclips)' },
    { id: 'som-g1-error-spotting', engine: 'standard-object-measurement', questionType: 'mcq', title: 'Spot measurement mistakes (Pennies)' },
    { id: 'som-g1-add-lengths', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Sum horizontal trains' },
    { id: 'som-g1-add-heights', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Sum vertical towers' },
    { id: 'som-g1-static-length', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Measure length (Static paperclips)' },
    { id: 'som-g1-static-height', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Measure height (Static pennies)' },
    { id: 'som-g1-copy-cubes-to-3', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Copy cubes (Sum up to 3)' },
    { id: 'som-g1-copy-cubes-to-5', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Copy cubes (Sum up to 5)' },
    { id: 'som-g1-copy-cubes-to-10', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Copy cubes (Sum up to 10)' },
    { id: 'som-g1-pattern-abab', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Patterns: Complete ABAB sequence' },
    { id: 'som-g1-pattern-aabb', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Patterns: Complete AABB sequence' },
    { id: 'som-g1-sub-takeaway', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Subtraction: Take away cubes' },
    { id: 'som-g1-sub-compare', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Subtraction: Compare block trains' },
    { id: 'som-g1-place-value-blocks', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Place value: Tens and ones blocks' },
    { id: 'som-g1-fraction-strips', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Fractions: Equivalent strip parts' },
    { id: 'som-g1-multiplication-array', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Multiplication: Stacks array model' },
    { id: 'som-g1-graphing-bars', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Graphing: Built block charts' },
    { id: 'som-g1-place-value-50', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Place value: Numbers up to 50' },
    { id: 'som-g2-place-value-100', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Place value: Numbers up to 100' },
    { id: 'som-g2-place-value-hundreds', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Place value: Hundreds, tens, and ones' },
    { id: 'som-g3-place-value-thousands', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Place value: Thousands, hundreds, tens, and ones' },
    { id: 'som-g1-ten-frame-5', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Ten frame: Numbers up to 5' },
    { id: 'som-g1-ten-frame-10', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Ten frame: Numbers up to 10' },
    { id: 'som-g1-ten-frame-20', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Ten frame: Numbers up to 20' },
    { id: 'som-g1-number-bonds-5', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Number bonds: Pairs up to 5' },
    { id: 'som-g1-number-bonds-10', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Number bonds: Pairs up to 10' },
    { id: 'som-g1-number-line-10', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Number line: 0 to 10' },
    { id: 'som-g1-number-line-20', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Number line: 0 to 20' },
    { id: 'som-g2-number-line-100', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Number line: 0 to 100' },
    { id: 'som-g2-area-grid-small', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Area: Count squares (up to 4x4)' },
    { id: 'som-g2-area-grid-medium', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Area: Count squares (up to 6x6)' },
    { id: 'som-g2-area-grid-click', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Area: Click to fill the grid' },
    { id: 'som-g2-division-sharing', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Division: Share equally into groups' },
    { id: 'som-g1-money-coins', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'Money: Count rupee coins' },
    { id: 'som-g1-odd-even', engine: 'standard-object-measurement', questionType: 'mcq', title: 'Odd and even numbers' },
    { id: 'som-g2-custom-skill', engine: 'standard-object-measurement', questionType: 'fillInTheBlank', title: 'SOM Custom Skill' }
  ],
  'measurement': [
    { id: 'meas.compare.size', engine: 'measurement', questionType: 'mcq', title: 'Compare Object Sizes' },
    { id: 'meas.nonstandard', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Measure with Cubes' },
    { id: 'meas.ruler.reading', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Read Ruler' },
    { id: 'meas.ruler.compare', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Compare Rulers' },
    { id: 'meas.choose.tool', engine: 'measurement', questionType: 'mcq', title: 'Choose Measurement Tool' },
    { id: 'meas.choose.unit', engine: 'measurement', questionType: 'mcq', title: 'Choose Measurement Unit' },
    { id: 'meas.thermometer', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Read Thermometer' },
    { id: 'meas.liquid.volume', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Read Liquid Volume' },
    { id: 'meas.conversion.table', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Unit Conversion Table' },
    { id: 'meas.conversion.single', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Single Unit Conversion' },
    { id: 'meas.conversion.mixed', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Add Mixed Units' },
    { id: 'meas.wordproblems', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Measurement Word Problems' },
    { id: 'meas.precision.error', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Precision Error Analysis' },
    { id: 'meas.density', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Calculate Density' },
    { id: 'meas.balance.compare', engine: 'measurement', questionType: 'mcq', title: 'Compare Balance Weights' },
    { id: 'meas.balance.add', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Add Weight to Balance Scale' },
    { id: 'meas.balance.remove', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Remove Weight from Balance Scale' },
    { id: 'meas.balance.interactive', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Interactive Balance Scale' },
    { id: 'meas.dice.interactive', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Interactive Horizontal Dice' },
    { id: 'meas.dice.vertical', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Interactive Vertical Dice' },
    { id: 'meas.nonstandard.multi', engine: 'measurement', questionType: 'fillInTheBlank', title: 'Nonstandard Unit Measurement' },
    { id: 'meas.svg.tool.demo', engine: 'measurement', questionType: 'fillInTheBlank', title: 'SVG Tool Demo Template' }
  ],
  'story-math': [
    { id: 'story-math-lesson', engine: 'story-math', questionType: 'interactiveApplet', title: 'Story lesson: Magical Sharing Pizza' },
    { id: 'story-math-sandbox', engine: 'story-math', questionType: 'interactiveApplet', title: 'Sandbox: Pizza Kitchen' },
    { id: 'story-math-quiz', engine: 'story-math', questionType: 'interactiveApplet', title: 'Quiz game: Fractions Superhero' },
    { id: 'story-math-practice', engine: 'story-math', questionType: 'interactiveApplet', title: 'Interactive practice: Choose and share' },
    { id: 'story-math-demo-board', engine: 'story-math', questionType: 'interactiveApplet', title: 'Teaching board: Whole, halves, quarters' },
    { id: 'story-math-remediation', engine: 'story-math', questionType: 'interactiveApplet', title: 'Remediation: Fair shares scaffold' },
    { id: 'story-math-manipulative-lab', engine: 'story-math', questionType: 'interactiveApplet', title: 'Universal manipulative lab' },
    { id: 'story-math-fraction-bar', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: fraction bar' },
    { id: 'story-math-number-line', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: number line' },
    { id: 'story-math-clock', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: clock' },
    { id: 'story-math-balance-scale', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: balance scale' },
    { id: 'story-math-measuring-cup', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: measuring cup' },
    { id: 'story-math-thermometer', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: thermometer' },
    { id: 'story-math-base-ten-blocks', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: base-ten blocks' },
    { id: 'story-math-place-value-chart', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: place value chart' },
    { id: 'story-math-diagram-labeling', engine: 'story-math', questionType: 'interactiveApplet', title: 'Manipulative: diagram labeling' }
  ],
  'interactive-tools': [
    { id: 'interactive-tools-fraction-bar', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: fraction bar' },
    { id: 'interactive-tools-number-line', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: number line' },
    { id: 'interactive-tools-clock', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: clock' },
    { id: 'interactive-tools-balance-scale', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: balance scale' },
    { id: 'interactive-tools-measuring-cup', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: measuring cup' },
    { id: 'interactive-tools-thermometer', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: thermometer' },
    { id: 'interactive-tools-base-ten-blocks', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: base-ten blocks' },
    { id: 'interactive-tools-place-value-chart', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: place value chart' },
    { id: 'interactive-tools-diagram-labeling', engine: 'interactive-tools', questionType: 'interactiveTool', title: 'Interactive tool: diagram labeling' }
  ],
  'cube-tools': [
    { id: 'cube_tools.build', engine: 'cube-tools', questionType: 'interactiveTool', title: 'Build a number with cubes' },
    { id: 'cube_tools.add', engine: 'cube-tools', questionType: 'interactiveTool', title: 'Add with two cube groups' },
    { id: 'cube_tools.subtract', engine: 'cube-tools', questionType: 'interactiveTool', title: 'Take away cubes' },
    { id: 'cube_tools.missing_addend', engine: 'cube-tools', questionType: 'interactiveTool', title: 'Build the missing addend' }
  ],
  'time': [
    { id: 'v1_days_of_week', engine: 'time', questionType: 'fillInTheBlank', title: 'Days of Week (Easy)' },
    { id: 'v2_seasons', engine: 'time', questionType: 'fillInTheBlank', title: 'Seasons (Easy)' },
    { id: 'v3_calendar', engine: 'time', questionType: 'fillInTheBlank', title: 'Calendar (Easy)' },
    { id: 'v4_months', engine: 'time', questionType: 'fillInTheBlank', title: 'Months of Year (Easy)' },
    { id: 'v5_am_pm', engine: 'time', questionType: 'fillInTheBlank', title: 'AM / PM (Easy)' },
    { id: 'order_days', engine: 'time', questionType: 'fillInTheBlank', title: 'Order Days' },
    { id: 'order_seasons', engine: 'time', questionType: 'fillInTheBlank', title: 'Order Seasons' },
    { id: 'm1_days_of_week', engine: 'time', questionType: 'fillInTheBlank', title: 'Days of Week (Medium)' },
    { id: 'm2_seasons', engine: 'time', questionType: 'fillInTheBlank', title: 'Seasons (Medium)' },
    { id: 'm3_calendar', engine: 'time', questionType: 'fillInTheBlank', title: 'Calendar (Medium)' },
    { id: 'm4_months', engine: 'time', questionType: 'fillInTheBlank', title: 'Months of Year (Medium)' },
    { id: 'm5_days_in_month', engine: 'time', questionType: 'fillInTheBlank', title: 'Days in Month' },
    { id: 'm6_relate_time_units', engine: 'time', questionType: 'fillInTheBlank', title: 'Convert Time Units' },
    { id: 'm7_am_pm', engine: 'time', questionType: 'fillInTheBlank', title: 'AM / PM (Medium)' },
    { id: 'o1_analogue_clock', engine: 'time', questionType: 'fillInTheBlank', title: 'Analogue Clock Reading' },
    { id: 'o2_digital_clock', engine: 'time', questionType: 'fillInTheBlank', title: 'Digital Clock Reading' },
    { id: 'o3_read_clock', engine: 'time', questionType: 'fillInTheBlank', title: 'Read & Write Clock Time' },
    { id: 'o4_am_pm', engine: 'time', questionType: 'fillInTheBlank', title: 'AM / PM (Hard)' },
    { id: 'o5_elapsed_time', engine: 'time', questionType: 'fillInTheBlank', title: 'Calculate Elapsed Time' },
    { id: 'o7_time_patterns', engine: 'time', questionType: 'fillInTheBlank', title: 'Time Patterns' },
    { id: 'o8_match_digital_clock', engine: 'time', questionType: 'fillInTheBlank', title: 'Match Digital to Analogue Clock' },
    { id: 'o9_match_analog_clock_words', engine: 'time', questionType: 'fillInTheBlank', title: 'Match Analogue to Words' },
    { id: 'match_digital_clock', engine: 'time', questionType: 'fillInTheBlank', title: 'Match Digital' },
    { id: 'match_analog_clock_words', engine: 'time', questionType: 'fillInTheBlank', title: 'Match Analog Clock' }
  ],
  'shapes': [
    { id: 'shapes.identify.visual-to-text', engine: 'shapes', questionType: 'mcq', title: 'Identify Shape (Visual to Text)' },
    { id: 'shapes.identify.text-to-visual', engine: 'shapes', questionType: 'mcq', title: 'Identify Shape (Text to Visual)' }
  ],
  'gk': [
    { id: 'gk_identify_person_v1', engine: 'gk', questionType: 'mcq', title: 'Identify Famous Persons' },
    { id: 'gk_identify_image_v1', engine: 'gk', questionType: 'mcq', title: 'Identify from Images' },
    { id: 'gk_trivia_v1', engine: 'gk', questionType: 'mcq', title: 'Personality Trivia' },
    { id: 'gk_fill_blanks_v1', engine: 'gk', questionType: 'fillInTheBlank', title: 'Fill in the Blanks Trivia' },
    { id: 'gk_match_v1', engine: 'gk', questionType: 'matching', title: 'Match Personality to Title' },
    { id: 'gk_sort_people_v1', engine: 'gk', questionType: 'categorization', title: 'Sort Leaders vs Sports Persons' },
    { id: 'gk_true_false_v1', engine: 'gk', questionType: 'mcq', title: 'True or False Facts' },
    { id: 'gk_misconception_v1', engine: 'gk', questionType: 'mcq', title: 'Spot the Truth' },
    { id: 'gk_inference_v1', engine: 'gk', questionType: 'mcq', title: 'Inference Questions' },
    { id: 'gk_multi_select_v1', engine: 'gk', questionType: 'mcq', title: 'Multi-Select Challenge' },
    { id: 'gk_key_points_v1', engine: 'gk', questionType: 'mcq', title: 'Personality Key Points' }
  ],
  'grammar': [
    { id: 'grammar.noun.identify', engine: 'grammar', questionType: 'fillInTheBlank', title: 'Identify Noun in Sentence' },
    { id: 'grammar.noun.classify', engine: 'grammar', questionType: 'mcq', title: 'Classify Noun Type' },
    { id: 'grammar.noun.sort', engine: 'grammar', questionType: 'categorization', title: 'Sort Nouns' },
    { id: 'grammar.pronoun.choose', engine: 'grammar', questionType: 'mcq', title: 'Choose Pronoun' },
    { id: 'grammar.pronoun.replace', engine: 'grammar', questionType: 'mcq', title: 'Replace with Pronoun' },
    { id: 'grammar.verb.identify', engine: 'grammar', questionType: 'mcq', title: 'Identify Verb' },
    { id: 'grammar.verb.tense', engine: 'grammar', questionType: 'mcq', title: 'Verb Tense Match' },
    { id: 'grammar.adjective.identify', engine: 'grammar', questionType: 'mcq', title: 'Identify Adjectives' },
    { id: 'grammar.article.choose', engine: 'grammar', questionType: 'mcq', title: 'Choose Article (a/an/the)' },
    { id: 'grammar.article.sentence', engine: 'grammar', questionType: 'mcq', title: 'Article in Sentence' },
    { id: 'grammar.sentence.type', engine: 'grammar', questionType: 'mcq', title: 'Sentence Types' },
    { id: 'grammar.sentence.punctuation', engine: 'grammar', questionType: 'mcq', title: 'Sentence Punctuation' },
    { id: 'grammar.sentence.capitalization', engine: 'grammar', questionType: 'mcq', title: 'Sentence Capitalization' }
  ]
};
