export const RATIO_MICRO_SKILLS = {
  ratio_visual_count: {
    skillId: "ratio_visual_count",
    title: "Visual Ratio Count",
    description: "Determine the ratio of objects using visual groups (e.g. shapes, emojis).",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: [],
    templates: ["ratio_visual_count"],
    difficultyRange: { min: "easy_visual", max: "easy_numeric" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_compare_same_kind: {
    skillId: "ratio_compare_same_kind",
    title: "Compare Quantities of Same Kind",
    description: "Identify comparisons between quantities of the same physical type.",
    competencyId: "ratio_foundations",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_visual_count"],
    templates: ["ratio_same_kind_check"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["unlike_quantities_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_compare_by_subtraction: {
    skillId: "ratio_compare_by_subtraction",
    title: "Compare Quantities by Subtraction",
    description: "Differentiate subtraction-based difference comparison from division ratio.",
    competencyId: "ratio_foundations",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_compare_same_kind"],
    templates: ["ratio_subtraction_vs_division"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["subtraction_vs_ratio_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_compare_by_division: {
    skillId: "ratio_compare_by_division",
    title: "Compare Quantities by Division",
    description: "Explain how a ratio functions as comparison by division.",
    competencyId: "ratio_foundations",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_compare_by_subtraction"],
    templates: ["ratio_subtraction_vs_division"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["subtraction_vs_ratio_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_identify_from_words: {
    skillId: "ratio_identify_from_words",
    title: "Ratio Notation from Words",
    description: "Write a ratio in standard colon notation from a word description.",
    competencyId: "ratio_foundations",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_visual_count"],
    templates: ["ratio_identify_from_words"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 5, smartScore: 80 }
  },
  ratio_terms_antecedent: {
    skillId: "ratio_terms_antecedent",
    title: "Terms: Antecedent",
    description: "Identify the antecedent (first term) of a ratio.",
    competencyId: "ratio_terms",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_identify_from_words"],
    templates: ["ratio_terms_antecedent_consequent"],
    difficultyRange: { min: "easy_numeric", max: "easy_numeric" },
    misconceptionTargets: ["antecedent_consequent_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_terms_consequent: {
    skillId: "ratio_terms_consequent",
    title: "Terms: Consequent",
    description: "Identify the consequent (second term) of a ratio.",
    competencyId: "ratio_terms",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_identify_from_words"],
    templates: ["ratio_terms_antecedent_consequent"],
    difficultyRange: { min: "easy_numeric", max: "easy_numeric" },
    misconceptionTargets: ["antecedent_consequent_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_simplify_two_terms: {
    skillId: "ratio_simplify_two_terms",
    title: "Simplify Two-Term Ratios",
    description: "Reduce a ratio of two numbers to its simplest form using HCF.",
    competencyId: "ratio_simplification",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_identify_from_words"],
    templates: ["ratio_simplify_two_terms"],
    difficultyRange: { min: "easy_numeric", max: "medium_simplify" },
    misconceptionTargets: ["hcf_not_used", "partial_simplification"],
    masteryCriteria: { consecutiveCorrect: 5, smartScore: 85 }
  },
  ratio_simplify_three_terms: {
    skillId: "ratio_simplify_three_terms",
    title: "Simplify Three-Term Ratios",
    description: "Reduce a ratio of three numbers to its simplest form.",
    competencyId: "ratio_simplification",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms"],
    templates: ["ratio_simplify_three_terms"],
    difficultyRange: { min: "medium_simplify", max: "hard_reasoning" },
    misconceptionTargets: ["hcf_not_used", "partial_simplification"],
    masteryCriteria: { consecutiveCorrect: 5, smartScore: 85 }
  },
  ratio_equivalent_scale_up: {
    skillId: "ratio_equivalent_scale_up",
    title: "Equivalent Ratios (Scale Up)",
    description: "Find an equivalent ratio by multiplying both terms by a factor.",
    competencyId: "ratio_equivalence",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms"],
    templates: ["ratio_equivalent_find"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["equivalent_ratio_scaling_error"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_equivalent_scale_down: {
    skillId: "ratio_equivalent_scale_down",
    title: "Equivalent Ratios (Scale Down)",
    description: "Find an equivalent ratio by dividing both terms.",
    competencyId: "ratio_equivalence",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms"],
    templates: ["ratio_equivalent_find"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["equivalent_ratio_scaling_error"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_equivalent_check: {
    skillId: "ratio_equivalent_check",
    title: "Check Equivalent Ratios",
    description: "Determine whether two given ratios are equivalent.",
    competencyId: "ratio_equivalence",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_equivalent_scale_up", "ratio_equivalent_scale_down"],
    templates: ["ratio_equivalent_check"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["equivalent_ratio_scaling_error"],
    masteryCriteria: { consecutiveCorrect: 5, smartScore: 80 }
  },
  ratio_missing_value: {
    skillId: "ratio_missing_value",
    title: "Find Missing Values",
    description: "Solve a ratio equivalence equation for a missing term (e.g. 2:3 = x:12).",
    competencyId: "ratio_equivalence",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_equivalent_check"],
    templates: ["ratio_missing_value"],
    difficultyRange: { min: "medium_missing_value", max: "hard_reasoning" },
    misconceptionTargets: ["missing_value_cross_multiply_error"],
    masteryCriteria: { consecutiveCorrect: 5, smartScore: 85 }
  },
  ratio_fraction_to_whole: {
    skillId: "ratio_fraction_to_whole",
    title: "Convert Fractional Ratios",
    description: "Simplify ratios containing fractions to whole number ratios using LCM.",
    competencyId: "ratio_fraction_ratios",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms"],
    templates: ["ratio_fraction_to_whole"],
    difficultyRange: { min: "medium_simplify", max: "hard_fraction" },
    misconceptionTargets: ["fraction_ratio_lcm_error"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_units_no_units: {
    skillId: "ratio_units_no_units",
    title: "Ratios Have No Units",
    description: "Understand and apply the rule that simplified ratios are unitless.",
    competencyId: "ratio_reasoning",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_identify_from_words"],
    templates: ["ratio_units_concept"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["unit_attached_to_ratio"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_unlike_quantities: {
    skillId: "ratio_unlike_quantities",
    title: "Unlike Quantities Check",
    description: "Validate if a ratio can be formed between different physical measurements.",
    competencyId: "ratio_reasoning",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_compare_same_kind"],
    templates: ["ratio_same_kind_check"],
    difficultyRange: { min: "easy_numeric", max: "medium_equivalent" },
    misconceptionTargets: ["unlike_quantities_confusion"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_word_problem_basic: {
    skillId: "ratio_word_problem_basic",
    title: "Basic Word Problems",
    description: "Solve practical real-world word problems using ratios.",
    competencyId: "ratio_word_problems",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms"],
    templates: ["ratio_word_problem_basic"],
    difficultyRange: { min: "medium_equivalent", max: "hard_word_problem" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 5, smartScore: 85 }
  },
  ratio_error_analysis: {
    skillId: "ratio_error_analysis",
    title: "Error Analysis",
    description: "Critically identify the error in a student's ratio calculation.",
    competencyId: "ratio_reasoning",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms", "ratio_equivalent_check"],
    templates: ["ratio_error_analysis"],
    difficultyRange: { min: "medium_simplify", max: "hard_reasoning" },
    misconceptionTargets: [],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 85 }
  },
  ratio_table_completion: {
    skillId: "ratio_table_completion",
    title: "Table Completion",
    description: "Fill in missing values in a ratio equivalence table.",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_missing_value"],
    templates: ["ratio_table_completion"],
    difficultyRange: { min: "medium_missing_value", max: "hard_reasoning" },
    misconceptionTargets: ["missing_value_cross_multiply_error"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 85 }
  },
  ratio_pattern_completion: {
    skillId: "ratio_pattern_completion",
    title: "Pattern Completion",
    description: "Extend a sequence of equivalent ratios.",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_table_completion"],
    templates: ["ratio_pattern_completion"],
    difficultyRange: { min: "medium_missing_value", max: "hard_reasoning" },
    misconceptionTargets: ["equivalent_ratio_scaling_error"],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 80 }
  },
  ratio_compare_greater: {
    skillId: "ratio_compare_greater",
    title: "Compare Greater Ratio",
    description: "Compare two ratios to determine which one is larger.",
    competencyId: "ratio_reasoning",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_equivalent_check"],
    templates: ["ratio_greater_comparison"],
    difficultyRange: { min: "medium_equivalent", max: "hard_reasoning" },
    misconceptionTargets: [],
    masteryCriteria: { consecutiveCorrect: 4, smartScore: 85 }
  },
  ratio_matching: {
    skillId: "ratio_matching",
    title: "Matching Ratios",
    description: "Match multiple unsimplified ratios to their simplest forms.",
    competencyId: "ratio_simplification",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_simplify_two_terms"],
    templates: ["ratio_matching"],
    difficultyRange: { min: "medium_simplify", max: "medium_simplify" },
    misconceptionTargets: ["hcf_not_used"],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  },
  ratio_sorting: {
    skillId: "ratio_sorting",
    title: "Sorting Ratios",
    description: "Sort ratios into equivalent categories.",
    competencyId: "ratio_equivalence",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_equivalent_check"],
    templates: ["ratio_sorting"],
    difficultyRange: { min: "medium_equivalent", max: "medium_equivalent" },
    misconceptionTargets: ["equivalent_ratio_scaling_error"],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  },
  ratio_remediation: {
    skillId: "ratio_remediation",
    title: "Ratio Remediation",
    description: "Scaffolded questions for addressing fundamental gaps in ratio concepts.",
    competencyId: "ratio_remediation",
    gradeBand: "G6",
    prerequisiteSkills: [],
    templates: ["ratio_remediation"],
    difficultyRange: { min: "easy_visual", max: "easy_numeric" },
    misconceptionTargets: [],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  },
  ratio_write_part_to_part_mcq: {
    skillId: "ratio_write_part_to_part_mcq",
    title: "Write a Part-to-Part Ratio",
    description: "Write the ratio of shapes in part-to-part MCQ form.",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_visual_count"],
    templates: ["ratio_write_part_to_part_mcq"],
    difficultyRange: { min: "easy_visual", max: "easy_visual" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  },
  ratio_write_colon_single_blank: {
    skillId: "ratio_write_colon_single_blank",
    title: "Write a Ratio Using a Colon",
    description: "Write the ratio of shapes using a colon with a single blank.",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_visual_count"],
    templates: ["ratio_write_colon_single_blank"],
    difficultyRange: { min: "easy_visual", max: "easy_visual" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  },
  ratio_write_fraction_single_blank: {
    skillId: "ratio_write_fraction_single_blank",
    title: "Write a Ratio Using a Fraction",
    description: "Write the ratio of shapes using a fraction with a single blank.",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_visual_count"],
    templates: ["ratio_write_fraction_single_blank"],
    difficultyRange: { min: "easy_visual", max: "easy_visual" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  },
  ratio_which_model_represents_mcq: {
    skillId: "ratio_which_model_represents_mcq",
    title: "Model Represents the Ratio",
    description: "Identify which model represents the given ratio.",
    competencyId: "ratio_visual_models",
    gradeBand: "G6",
    prerequisiteSkills: ["ratio_visual_count"],
    templates: ["ratio_which_model_represents_mcq"],
    difficultyRange: { min: "easy_visual", max: "easy_visual" },
    misconceptionTargets: ["order_confusion"],
    masteryCriteria: { consecutiveCorrect: 3, smartScore: 80 }
  }
};

